const herge = [
    {
        id: 1,
        firstName: 'Georges',
        lastName: 'REMI',
        nomArtiste: 'HERGE',
        picture: '1.jpg',
        nationalité: 'Belge',
        date_de_naissance: '22 Mai 1907',
        date_de_décès: '3 Mars 1983',
        presentation: 'Biographie courte de Hergé - Né en 1907 près de Bruxelles, le jeune Georges Remi est un enfant turbulent qui se passionne pour le dessin. Il subit l\'occupation allemande de la Première Guerre mondiale. Amateur de scoutisme durant son adolescence, ses premiers dessins sont publiés dans des revues scouts de Belgique. Il prend alors pour pseudonyme Hergé, formé à partir des initiales de son nom et prénom (RG). En 1925, il commence à travailler pour le journal Le Vingtième Siècle. Il se voit confier à partir de 1928 la responsabilité du lancement du Petit Vingtième, un supplément jeunesse comportant des pages de bandes dessinées. Dans cet hebdomadaire, Hergé va créer plusieurs personnages. Le plus célèbre d\'entre eux, Tintin, voit le jour en 1929. Les voyages de ce jeune reporter connaissent un succès retentissant en Belgique dès les premières semaines de parution.En 1932, Hergé épouse sa première femme Germaine Kieckens. Au début de la Seconde Guerre mondiale, la Belgique est annexée par l\'Allemagne nazie. Le Vingtième Siècle cesse de paraitre et Hergé est engagé par le journal Le Soir, qui devient sous l\'occupation un journal collaborationniste. Après la Libération, Hergé est soupçonné de collaboration et d\'antisémitisme, comme beaucoup de personnes ayant travaillé au Soir. Il est pendant un temps interdit de publication. La création des Éditions du Lombard en 1946 permet la diffusion du Journal de Tintin et le retour d\'Hergé, nommé directeur artistique du projet. A partir des années 1950, le phénomène Tintin prend une ampleur mondiale. Des adaptations et produits dérivés voient le jour dès 1959. Fatigué par plusieurs épisodes de dépression et des problèmes de santé, Hergé ne peut plus garder la même productivité qu\'auparavant. En 1977, il divorce et se remarie avec Fanny Rodwell, aujourd\'hui propriétaire d\'une partie des droits sur l’œuvre de son mari. Hergé s\'éteint en 1983 à l\'âge de 75 ans.',
        aventures_de_tintin: "Hergé crée le personnage de Tintin en 1929, alors qu'il cherche de nouvelles idées de personnages à intégrer dans Le Petit Vingtième. L'apparence de Tintin est probablement inspirée du personnage de Totor, dessiné par Hergé entre 1926 et 1930 pour Le Boy-scout belge. Il va faire vivre à ce jeune reporter et son fidèle chien Milou de nombreuses enquêtes à travers le monde. La première se déroule en URSS et est intitulée Tintin au pays des Soviets. L'idée a été soumise à Hergé par le directeur du Vingtième siècle, Norbert Wallez, hostile aux idées communistes et fervent admirateur de Mussolini. Cette bande dessinée hebdomadaire gagne en popularité en Belgique et attire l'attention de la maison d'éditions Casterman. Hergé y signe un contrat en 1934 pour compiler et publier Les Aventures de Tintin en albums. C'est vers cette période que l'auteur commence à effectuer des recherches plus poussées pour ses histoires. Sa rencontre et son amitié avec le sculpteur Zhang Chongren, alors étudiant, a une influence dans sa manière de raconter l'histoire du Lotus bleu. Hergé a collaboré avec d'autres auteurs de bandes dessinées célèbres comme Edgar P . Jacobs et Jacques Martin. Ces derniers l'ont aidé pour la refonte graphique et la colorisation, mais conseillent aussi Hergé sur les histoires de Tintin. La dernière aventure, Tintin et l'Alph-Art, est publiée à titre posthume et demeure inachevée. La série est aujourd'hui vendue à plusieurs centaines de millions d'exemplaires et traduite dans près d'une centaine de langues."
    }
];

module.exports = herge