const series = [
    {
        id: 1,
        nom: 'Ben Kalish Ezab',
        prenom: 'Abdallah',
        picture: '1.jpg',
        profession: 'Fils de Mohammed Ben Kalish Ezab',
        personnage: "Le prince Abdallah est manifestement la caricature de l’enfant-roi : on ne peut littéralement rien lui refuser, et il n’a pas son pareil pour pousser les adultes à bout. Tout comme dans Tintin au pays de l’or noir, le garnement multiplie dans Coke en stock les provocations en tous genres, que ce soit à l’égard du capitaine Haddock, de Milou, du professeur Tournesol ou de Tintin lui-même, quand ce n’est pas au détriment de ce pauvre Nestor, que l’on verra à la fin de cette seconde aventure complètement épuisé par les polissonneries de ce turbulent gamin. Hergé affirmait s’être inspiré de détails vécus pour créer ce jeune serpent à ressort. « Abdallah, le petit enfant gâté insupportable, j’en connais, et vous en connaissez cer- tainement, vous aussi. »",
    },
    {
        id: 2,
        nom: 'Thompson',
        prenom: 'Allan',
        picture: '2.jpg',
        profession: 'Marin, contrebandier',
        personnage: "Allan, c’est l’archétype de la canaille prêt à tout pour arriver à ses fins. Sur ses traces, Tintin n’est pas encore monté à bord du Karaboudjan qu’il le vise d’emblée par une tentative de meurtre. À peine celle-ci aura-t-elle échoué qu’il enlève le reporter et entend l’envoyer par le fond avec un poids de fonte aux pieds.S’il est le chef de la bande, c’est aussi un éternel homme de main, un exécuteur de basses oeuvres qui doit solliciter des ordres avant de commettre ses vilénies. C’est pour Omar Ben Salaad qu’il se livre à la contrebande d’opium dans des boîtes de faux crabe. C’est pour Rastapopoulos, alias le marquis di Gorgonzola, qu’il trafique de la drogue de la mer Rouge vers les Indes (dans Les Cigares du Pharaon) puis des esclaves dans le golfe arabique (dans Coke en stock). Pour le même, il dirige dans Vol 714 pour Sydney une tripotée de gros bras qui prennent le contrôle d’une petite île de la mer des Célèbes pour mieux détourner le jet et les milliards de Laszlo Carreidas.",
    },
    {
        id: 3,
        nom: 'Perez',
        prenom: 'Alonzo',
        picture: '3.jpg',
        profession: 'Escroc',
        personnage: "Ces deux malfrats sont complices et feront tout pour voler le diamant qui se cache dans le fétiche à l’oreille cassée.",
    },
    {
        id: 4,
        nom: 'Filoselle',
        prenom: 'Aristide',
        picture: '4.jpg',
        profession: 'Fonctionnaire retraité, pickpocket, collectionneur de portefeuille',
        personnage: "Cet honorable citoyen atteint de kleptomanie a réussi à constituer une imposante collection personnelle de portefeuilles volés à la tire. Nous citerons à titre documentaire, un portefeuille subtilisé au père de Jo et Zette, Monsieur Legrand, le 25.12.1942, un autre subtilisé à Maxime Loiseau, le 12.10.1942 ; et enfin une étonnante série portant le nom de Dupond et Dupont. Filoselle tire une certaine fierté de ses activités. Il garde à cet effet des coupures de presse sur les pickpockets et les voleurs de portefeuilles.",
    },
    {
        id: 5,
        nom: 'Bada',
        prenom: 'Ramon',
        picture: '5.jpg',
        profession: 'Escroc',
        personnage: "Ces deux malfrats sont complices et feront tout pour voler le diamant qui se cache dans le fétiche à l’oreille cassée.",
    },
    {
        id: 6,
        nom: 'Balthazar',
        prenom: 'Juan',
        picture: '6.jpg',
        profession: 'Fabricant, artisan',
        personnage: "Frère du peintre-sculpteur Balthazar trouvé mort à son domicile sis 21, rue de Londres, Balthazar J. produit en série des fétiches arumbayas sur base de l’original trouvé dans une malle ayant appartenu à feu son frère. Son look fait plus penser à un laborantin qu’à un spécialiste en reproduction d’art primitif.",
    },
    {
        id: 7,
        nom: 'Barnabé',
        prenom: 'Rémon',
        picture: '7.jpg',
        profession: 'Indicateur, rabatteur',
        personnage: "Un des protagonistes de l’histoire 'Le Secret de La Licorne' qui travaille pour les frères Loiseau, antiquaires de leur état. Il est chargé par les frères Loiseau de découvrir les deux autres maquettes de La Licorne. Il connaîtra un destin funeste. Il est abattu par ses mandants qui craignent qu’il ne parle.",
    },
    {
        id: 8,
        nom: 'Baxter',
        prenom: 'Thomas',
        picture: '8.jpg',
        profession: 'Directeur centre de recherches atomiques de Sbrodj',
        personnage: "M. Baxter est le directeur du Centre de recherches atomiques de Sbrodj. Ce centre, situé en Syldavie, développe, secrètement avec l’aide du professeur Tournesol, des activités de recherche pour la construction d'une fusée pour aller sur la Lune. M. Baxter est affable mais quand les choses deviennent sérieuses, il ne mâche pas ses mots.",
    },
    {
        id: 9,
        nom: 'Bazaroff',
        prenom: 'Basil',
        picture: '9.jpg',
        profession: 'Marchand d\'armes',
        personnage: "Le modèle qui a inspiré le personnage de Bazaroff (« Mazaroff » dans la version noir et blanc) est Basil Zaharoff. Sir Basil Zaharoff d'origine grecque fit preuve d'un tel sens des affaires qu'il sut se rendre indispensable aux dirigeants des grandes puissances. Il vendait des armes à n'importe quel camp, soutenu dans ses démarches par des politiciens et des puissances bancaires à sa dévotion. Dans Le Crapouillot, il est cité parmi les puissants de ce monde. Celui-ci devient dans L'Oreille cassée Basil Bazaroff, marchand d'armes également. Bazaroff agit via la Vicking Arms Co. Ltd et vend sa camelote guerrière au San Théodoros et Nuevo Rico et par l’intermédiaire de son complice R.W. Chicklet tente d’ériger ces deux pays l’un contre l’autre à propos de la région Gran Chapo riche en pétrole. Le préfixe choisi par Hergé pour créer le nom à consonance russe en dit long sur le regard qu’il porte sur ce type de marchand.",
    },
    {
        id: 10,
        nom: 'Castafiore',
        prenom: 'Bianca',
        picture: '10.jpg',
        profession: 'Cantatrice',
        personnage: "Bianca Castafiore signifie littéralement 'blanche chaste-fleur'. Bianca est également couramment surnommée 'Le rossignol milanais'. Selon Hergé, Bianca Castafiore serait âgée de 45 ans. Bien que la presse l'a fiancée successivement à diverses personnalités, le rossignol milanais n'a en vérité pas de famille connue. Son entourage proche est composé exclusivement de sa fidèle accompagnatrice Irma, ainsi que de son pianiste Igor Wagner. Procédant de la même façon que pour Tintin et Haddock, Hergé réunit plusieurs ingrédients pour façonner le personnage de la Castafiore. En premier lieu, il se souvint que, lorsqu'il était encore enfant, sa tante Ninie, accompagnée au piano, régalait la famille Remi des puissantes inflexions de sa voix perçante. Ses interprétations ne firent rien pour nourrir chez lui un quelconque amour de la musique, pour ne rien dire de l'opéra, qui pût égaler son enthousiasme précoce pour le dessin, puis sa passion pour les arts visuels. En fait, elles ont sans doute contribué à renforcer son inaptitude à trouver le moindre attrait à l'opéra, une forme d'expression artistique qu'il considérait comme assez ridicule et peu crédible.  L'opéra m'ennuie , confia-t-il à Numa Sadoul,  je l'avoue à ma grande honte ! Ou alors il me fait rire.  Rien d'étonnant, dès lors, s'il a créé une cantatrice archétypale qui nous fait sourire. Partant de ce stéréotype, dont Tintin et le lecteur croisent la route pour la première fois dans Le Sceptre d'Ottokar, Hergé va raffiner et enrichir son personnage au fil de ses apparitions ultérieures. C'est dans les années 1950 qu'Hergé trouva son véritable modèle pour la Castafiore, quand les journaux et les magazines d'actualités comme Paris-Match, l'une des ses sources de documentation privilégiées, rapportaient par le menu les moindres faits de la prodigieuse carrière professionnelle et de la vie privée de Maria Callas. Ses interprétations légendaires à Milan, New York, Chicago, Londres et Paris mirent le monde à ses pieds. En 1964, Sir David Webster, le directeur de Covent Garden à Londres, la présenta comme  la plus grande artiste lyrique de notre époque . Elle était  La Divine, la cantatrice la plus célèbre de l'époque. ",
        personnage_suite: "Elle les essaie et, se regardant dans un miroir, est éblouie par le spectacle. Sur un tempo de valse, elle déclame :  Ah ! Je ris de me voir si belle en ce miroir ? Est-ce toi, Marguerite, est-ce toi ?  Le rôle de Marguerite fut créé en 1859 par Marie Miolan-Carvalho dont la tessiture de soprano colorature lyrique - dramatique ne trouva d'équivalent qu'un siècle plus tard avec Maria Callas. Si elle est, c'est un fait, d'une vanité insondable, Bianca Castafiore, il faut le souligner, fait preuve dans les Aventures de deux qualités plus qu'éminentes : la loyauté et le courage. Lorsque, dans L'Affaire Tournesol , elle n'a pas hésité à risquer de se compromettre et a cacher Tintin et Haddock dans sa penderie alors que le lubrique Sponsz, qui n'est pas sans rappeler l'odieux Scarpia de Tosca dans l'opéra de Puccini, fait irruption dans sa loge. Son courage se manifeste aussi avec éclat durant sa comparution au palais de Justice de Tapiocapolis. Elle se fait une beauté, tandis que le procureur profère ses éructations. Le réquisitoire incendiaire résonne dans le prétoire : Contre cette sirène au cœur de vipère, conte ce monstre à la voix d'or, je demande, je requiers, j'exige : la prison à vie ! Loin de se laisser abattre, elle ne cache pas son mépris pour ce réquisitoire absurde, le dit, et entonne avec sa vigueur habituelle l'air de Bijoux. Si elle chante les bijoux, elle éprouve une véritable passion obsessionnelle à leur égard. Maria Callas, reine de la jet-society des années 1950, collectionne aussi les joyaux d'une rare qualité durant sa liaison passionnée avec l'armateur grec Aristote Onassis. Si les sentiments de Tournesol restent sans écho, Haddock paraît plus 'chanceux'. Ses malheurs successifs dans Les Bijoux raniment l'instinct maternel de la prima donna. Elle est aux petits soins pour lui, elle soulage la piqûre de guêpe, elle le promène dans son fauteuil roulant à travers le parc. Rien d'étonnant, dès lors, si les journalistes de Paris-Flash, allusion à peine voilée à Paris-Match, échafaudent une possible idylle, voire un projet de mariage."
    },
    {
        id: 11,
        nom: 'Bikoulou',
        prenom: 'Bikoulou',
        picture: '11.jpg',
        profession: 'Guerrier',
        personnage: "Indien de la tribu arumbaya qui ne rate pas l’occasion de se rattraper de son erreur en ayant livré Milou au sorcier et sauve Milou d’une mort assurée grâce à sa sagacité.  Il brave les sortilèges du sorcier de la tribu au risque d’être transformé en grenouille en alertant Ridgewell.",
    },
    {
        id: 12,
        nom: 'Bohlwinkel',
        prenom: 'Lotus',
        picture: '12.jpg',
        profession: 'Banquier, financier',
        personnage: "Il dirige la banque Bohlwinkel de Sao Rico. Ayant eu vent de l’expédition du professeur Calys par les médias, sa banque finance une expédition concurrente (celle du Peary) en vue de s’approprier avant Tintin le métal précieux présent dans l’aérolithe, baptisé par la suite « calystène ».",
    },
    {
        id: 13,
        nom: 'Jorgen',
        prenom: 'Boris',
        picture: '13.jpg',
        profession: 'Colonel, militaire',
        personnage: "En réalité cet homme de confiance participe à un complot contre son Roi. Les ennemis se trouvent souvent parmi nous ou parmi les proches. Méfiance donc mais Tintin n’est pas dupe et son sens de la perspicacité lui permet de démasquer ce comploteur qu’on retrouvera dans le diptyque des Aventures lunaires sous le nom de Colonel Jorgen, passager clandestin de la fusée lunaire.",
    },
    {
        id: 14,
        nom: 'Boullu',
        prenom: 'Isidore',
        picture: '14.jpg',
        profession: 'Marbrier',
        personnage: "Isidore Boullu, est quelqu’un sur lequel on ne peut pas compter... Sous des dehors débonnaires d’homme banal et ordinaire, Isidore Boullu cache mal sa perversité et ses mensonges. Isidore Boullu a pris le pli de prendre la vie du bon côté et de ne jamais s’énerver. Il promet toujours et ne tient presque jamais promesse. Par contre, il peut participer, en pleine journée, à une aubade donnée par la modeste harmonie de Moulinsart, histoire de boire un petit coup à l’oeil. Les clients ? Les urgences ? Il a bien le temps.",
    },
    {
        id: 15,
        nom: 'Gibbons',
        prenom: 'Walter.R.',
        picture: '15.jpg',
        profession: 'homme d\'affaires, chef d\'entreprise',
        personnage: "Directeur de l’American & Chinese Steel Company à Shangai, il est le prototype même du colonial méprisant à l’égard des populations autochtones. Sans gêne, brutal, xénophobe, imbu de sa personne, il est intimement convaincu de la supériorité de sa race. Assistant à une scène où Gibbons maltraite un conducteur de pousse-pousse, Tintin lui administrera une bonne correction. Humilié, il dénoncera le héros aux autorités japonaises, avec la complicité de Dawson, chef de la police de la concession internationale de Shangai.",
    },
    {
        id: 16,
        nom: 'Smiles',
        prenom: 'Bobby',
        picture: '16.jpg',
        profession: 'Bandit, chef de bande',
        personnage: "Rescapé miracle du massacre de la Saint-Valentin, Moran a pu inspirer le personnage de Smiles. Quand le personnage de Bobby Smiles (en français, « Robert Sourit ») apparaît dans Tintin en Amérique, c’est comme chef du G.S.C., le syndicat des gangsters de Chicago, une association qu’il affirme être concurrente de celle du terrible Al Capone. Bobby Smiles, chef d’une bande rivale de Capone, pourrait donc avoir comme modèle un certain George Moran, chef du gang des quartiers nord, et cible du massacre connu sous le nom : Massacre de la Saint-Valentin. Dès le début de sa carrière, Bobby Smiles passe pour un individu louche et dangereux. Il compte parmi ses sbires un faux shérif, prompt à lui livrer Tintin sur un plateau. Sur la porte de son bureau, une pancarte de la police dissimule sa véritable activité: celle d’un membre éminent du G.S.C., le Syndicat des gangsters de Chicago ! Parmi les sources d’inspiration pour le personnage de Bobby Smiles, on cite George Moran mais aussi Spike O’Donnell, dont la ressemblance avec le gangster d’Hergé est saisissante.",
    },
    {
        id: 17,
        nom: 'Siclone',
        prenom: 'Philémon',
        picture: '17.jpg',
        profession: 'Egyptologue, archéologue',
        personnage: "Très distrait, Philémon Siclone cache peut-être un complice de Kih-Oskh. «Arrêtez-le !... Arrêtez-le !» D’emblée, la rencontre de Tintin avec Philémon Siclone, un égyptologue très distrait, débute sous le signe du quiproquo, puisque l’équipage pense que c’est Tintin qu’il faut arrêter ! De la même façon, l’égyptologue Philémon Siclone n’est pas toujours aussi net qu’on voudrait le croire. Il est très distrait et confond les manches à air avec les commandants de bord, il porte un prénom excentrique, quant au « cyclone », il fait sans doute référence au désordre que sa distraction provoque. Bon ou méchant ? La porte reste ouverte",
    },
    {
        id: 18,
        nom: 'Wang',
        prenom: 'Didi',
        picture: '18.jpg',
        profession: 'fils de Wang Jen-Ghié',
        personnage: "Il suit Tintin à son insu et lui sauve la vie par deux fois. Mitsuhirato veut se débarrasser de cet ange gardien et faire d’une pierre deux coups en empoisonnant Didi au moyen du radjaïdjah, le « poison-qui-rend-fou ». De la sorte, cet ange devient un fou incontrôlable. Son esprit ainsi piégé est au service de ce diable de Mitsuhirato. Lors de ses crises de folie, en vantant la gloire de Lao Tseu: « Il faut trouver la voie. » il tente à plusieurs reprises de couper la tête de Tintin et de Milou à l'aide d'un sabre. Il va même à vouloir tuer ses propres parents ! Il retrouvera la raison grâce à un remède du professeur Fan Se-Yeng.",
    },
    {
        id: 19,
        nom: 'Wang',
        prenom: 'Jen-Ghié',
        picture: '19.jpg',
        profession: 'homme politique, chef de la société secrete des Fils du Dragon',
        personnage: "Wang Jen-Ghié est le père du pauvre Didi, victime des effets du radjaïdjah, le terrible poison-qui-rend-fou, mais surtout le fondateur de la société des Fils du Dragon, qui lutte contre les ravages de l’opium en Chine. Allié indéfectible de Tintin dans ce combat qui l’oppose aussi à la bande de Roberto Rastapopoulos, il lutte aussi contre l’invasion japonaise. On appelle Monsieur Wang aussi Vénérable ; il porte certes des traces d’un âge avancé : sa barbe est blanche et il utilise une canne pour se déplacer. Mais les années n’ont émoussé en rien la force de sa détermination. Et c’est avec un calme étonnant, sans rien montrer de la colère qui le nourrit, qu’il agit pour contrer les actions malfaisantes de trafiquants d’opium qui empoisonnent sa patrie, sous la férule de Rastapopoulos et avec la complicité de Mitsuhirato, qui combine l’appât du gain avec les ambitions territoriales japonaises.",
    },
    {
        id: 20,
        nom: 'Philippulus',
        prenom: 'Arthur',
        picture: '20.jpg',
        profession: 'Savant, prédicateur, ancien collaborateur du professeur Calys',
        personnage: "Le prophète fou était inspiré d’un ami d’Hergé. « C’est le châtiment ! Faites pénitence !... La fin des temps est venue!» Si le personnage de Philippulus le prophète fait une apparition très remarquée au début de l’histoire de L’Étoile mystérieuse. Philippulus apparaît dans une trentaine de cases. Cet inquiétant personnage marquera durablement les esprits des jeunes lecteurs. Philippulus est un faux prophète : « Seul maître après dieu ».",
    },
    {
        id: 21,
        nom: 'Sakharine',
        prenom: 'Ivan-Ivanovitch',
        picture: '21.jpg',
        profession: 'Collectionneur d\'origine russe',
        personnage: "Cet étrange monsieur rencontré pour la première fois par Tintin au vieux marché est collectionneur de bateaux anciens ; comme tous les collectionneurs Ivan Ivanovitch Sakharine est capable de dépenser une fortune pour acquérir une pièce qui manque à sa collection. Ainsi, il propose à Tintin un prix sept fois plus élevé que celui du vieux brocanteur pour tenter de lui racheter « La Licorne ». Il possède une importante série d’ouvrages relatifs à la marine à voile et eut le grand privilège de posséder la maquette de l’une des trois « Licorne » du chevalier de Hadoque. Sakharine fut victime de Monsieur Barnabé, le rabatteur des frères Loiseau qui le chloroforma pour s’emparer du parchemin de La Licorne. Il resta apparemment en bons termes avec le capitaine Haddock et ses amis en acceptant de faire figurer son exemplaire de « La licorne » à l’inauguration de la salle de la Marine au Château de Moulinsart.",
    },
    {
        id: 22,
        nom: 'Nestor',
        prenom: 'Ernest',
        picture: '22.jpg',
        profession: 'Major d\'homme',
        personnage: "Nestor est le gardien du temple de Moulinsart. Secondaire, Nestor ? Cela reste à voir, tant son rôle est essentiel dans le fonctionnement du château de Moulinsart. Nestor y semble d’ailleurs avoir été domestique depuis toujours, sans doute même avant le rachat du château par les frères Loiseau, antiquaires filous sur la piste du trésor de La Licorne. La première qualité de Nestor est la fidélité... même s’il lui arrive d’écouter aux portes et de regarder par le trou de la serrure ! Nestor ignore que ses patrons sont des escrocs et c’est pour cela que, prenant Tintin pour un voleur, il l’assomme à coup de gourdin. Seul Tintin pourra lui éviter la prison en confirmant aux Dupondt que Nestor a été abusé par ses employeurs. Soutenu par Haddock, très persuasif... afin qu’une fois libéré, il puisse le ravitailler en cognac trois étoiles. Obséquieux mais jusq'ou ? Dès cet instant, Haddock le traite en serviteur, l’appelant par son prénom et lui donnant des instructions. Semble- t-il à la pleine satisfaction du maître d’hôtel. Respectueux des uns et des autres, ne protestant jamais, toujours prêt à servir, Nestor est-il si limpide que cela? Certes, ses parents lui ont donné le prénom du plus âgé et du plus sage des héros de la guerre de Troie. Mais notre maître d’hôtel, s’il est effacé, semble cultiver de sombres préjugés. Ainsi exprime-t-il clairement sa réprobation quand Haddock invite des gens du voyage, chassés d’un dépotoir, à camper sur les pelouses de Moulinsart. Et proteste-t-il vigoureusement quand «ces étrangers» dressent leur tente dans le salon du château... Nestor, actif au four et au moulin. Nestor ne recule devant rien pour rendre le séjour au château de Moulinsart agréable pour ses maîtres, mais aussi pour les invités de ce lieu prestigieux qu’il semble avoir toujours habité. Après son entrée dans le monde de Tintin, Nestor va devenir un personnage récurrent de la série, puisqu’il apparaît presque chaque fois quand l’action se déroule au château, parfois de manière très elliptique : dans Tintin au Tibet, Nestor, invisible, n’est cité que pour avoir fait suivre le courrier de Tchang jusqu’en Suisse !  ",
    },
    {
        id: 23,
        nom: 'Schultz',
        prenom: 'Irma',
        picture: '23.jpg',
        profession: 'Habilleuse',
        personnage: "Discrète et effacée, la camériste de Bianca Castafiore vit perpétuellement dans l’ombre de la tonitruante cantatrice. Elle est toujours vêtue avec une austérité très victorienne. Son calme apparent sera troublé à de nombreuses reprises lors de son peu reposant séjour à Moulinsart. Comme sa patronne, elle est assez sujette à des évanouissements fréquents et poussée à bout elle pique finalement une crise de nerfs. Dans Les Bijoux de la Castafiore, les Dupondt faillirent faire les frais d’une de ses crises. Elle frôla le peloton d’exécution au San-Théodoros.  ",
    },
    {
        id: 24,
        nom: 'Bjorgenskjold',
        prenom: 'Erik',
        picture: '24.jpg',
        profession: 'Savant, chercheur',
        personnage: "Savant suédois, Erik Björgenskjöld a participé à l’expédition polaire à bord de l’Aurore (L’Étoile mystérieuse). Il est également l’auteur d’un ouvrage sur les protubérances solaires.   ",
    },
    {
        id: 25,
        nom: 'Sponz',
        prenom: 'Kjorg',
        picture: '25.jpg',
        profession: 'Chef de la police secréte, militaire, conseiller politique',
        personnage: "Inspiré graphiquement par le propre frère d’Hergé, le colonel bordure agit comme l’exemple parfait du malfaisant sans conscience. Pour un héros aussi exceptionnel que Tintin, il faut des malfaisants à la hauteur ! Et c’est clairement dans la catégorie des sombres génies que joue le colonel Sponsz, chef de la police secrète de Bordurie (L’Affaire Tournesol). Sponsz, c’est un Tintin passé du côté du Mal... Mais les deux hommes ne se sont jamais perdus de vue. Et, dans L’Affaire Tournesol, en 1956, Hergé, ainsi qu’il le confie à Numa Sadoul, utilise le port de tête et la tonsure de son frère pour camper le détestable Sponsz. Hergé confiait aussi que le personnage, « manifestement allemand », était inspiré d’Erich von Stroheim. L’acteur et réalisateur était en fait d’origine austro- hongroise, mais c’est évidemment dans le rôle du commandant à la minerve dans La Grande Illusion, réalisé par Jean Renoir en 1937, qu’il marque davantage l’inconscient collectif. Toujours tiré à quatre épingles, la tonsure parfaite, le colonel Sponsz se pique de culture classique et fréquente l’opéra ! On le retrouve dans Tintin et les Picaros où il est devenu le conseiller technique de Tapioca.",
    },
    {
        id: 26,
        nom: 'Alvarez',
        prenom: 'Ricardo',
        picture: '26.jpg',
        profession: 'Colonel, militaire',
        personnage: "Il est de nationalité san-théodorienne et l’aide de camp de son excellence le général Tapioca. Ce digne et souriant colonel possède une élégante moustache à la Salvador Dali sans toutefois posséder le talent et l’humour de l’universel génie. Alvarez cache, sous le poids de ses médailles et décorations, un cœur de sombre fripouille. Totalement dévoué au dictateur sans-théodorien, il n’hésite pas à emmener Tintin et ses amis dans un traquenard au sommet de la pyramide de Trenx Coalt. Alvarez n’a aucune honte à « tourner la veste » quand les choses tournent au vinaigre. Sa réaction à la chute de Tapioca est sans équivoque : Toutes mes félicitations, mon général... ! Et mort à Tapioca ! Faut-il le faire fusiller tout de suite ? ».",
    },
    {
        id: 27,
        nom: 'Cuehlo',
        prenom: 'Pablo',
        picture: '27.jpg',
        profession: 'homme de main',
        personnage: "Dans la version noir et blanc, Pablo (Paul en français) s’appelait Manuel Paolino ! C’est lui qui est chargé d’éliminer Tintin pour 5000 dollars. Son mandant est un certain Rodriguez, lui même homme de paille de R.W. Chicklet. Pablo, ce méchant qui complote contre le juste, se repentira envers Tintin après que ce dernier, pris d’un sentiment de tempérance et de pitié, le laisse partir lors de la tentative d’assassinat contre sa personne. Pablo sauvera Tintin du peloton d’exécution en organisant son évasion. Dans Tintin et les Picaros, Pablo fait partie du casting ! Il cultive non pas le meilleur de sa nature mais le pire puisqu’il participe au plan machiavélique du Colonel Sponsz pour faire éliminer Tintin, ses amis et par la même occasion le général Alcazar en pleine jungle ! À la fin récit, Tintin lui pardonne à nouveau cette trahison !",
    },
    {
        id: 28,
        nom: 'Calys',
        prenom: 'Hippolyte',
        picture: '28.jpg',
        profession: 'Savant, directeur de l\'observatoire',
        personnage: "Calys, la tête perdue dans les étoiles Hippolyte Calys, avant un certain Tournesol, est l’archétype du savant distrait... Hippolyte Calys ? C’est sans doute ce que Les Aventures de Tintin ont connu de mieux comme savant excentrique... avant l’arrivée de Tournesol. Calys affiche un prénom désuet, qui annonce d’emblée, comme un blason, ce décalage permanent avec la réalité. Il le prêtera bientôt à l’exubérant Bergamotte... Calys, « caliche » en bruxellois, signifie « réglisse », un comble pour un homme qui aime les caramels mous, mais surtout qui en propose de manière abrupte au milieu d’une conversation sur la fin du monde, ce qui ne manque pas de stupéfier Tintin... S’il n’a pas de modèle «authentique» connu, Calys est clairement l’héritier d’un personnage de fiction, Pancrace Eusèbe Zéphyrin Brioché, dit «le savant Cosinus». Dans cette bande dessinée réalisée par Christophe dès 1893, ce savant, censé faire le tour du monde, invente les moyens de transport les plus farfelus, mais ceux-ci ne sortent que de très peu des frontières de Paris. Avec Calys, Hergé incarne le savant qui combine le comique d’une distraction appuyée avec une profonde érudition, permettant de fournir des données scientifiques complexes.",
    },
    {
        id: 29,
        nom: 'Caraco',
        prenom: 'Dull',
        picture: '29.jpg',
        profession: 'Guide',
        personnage: "Guide pusillanime, il abandonne lâchement Tintin en pleine jungle alors qu’il devait le mener à la tribu des Arumbayas. Il n’en est pas pour autant fourbe puisqu’il laisse le canot à Tintin qui peut poursuivre sa route seul !",
    },
    {
        id: 30,
        nom: 'Caraidas',
        prenom: 'Lazlo',
        picture: '30.jpg',
        profession: 'Constructeur d\'avions, homme d\'affaires',
        personnage: "S’il y a une personnalité qui sort de l’ordinaire dans la galerie de portraits créée par Hergé, c’est bien celle du milliardaire Laszlo Carreidas. L’homme, très riche, ne laisse pourtant rien paraître de son état de fortune, car ses vêtements ne sont certes pas à l’image de sa condition sociale. Mais ce qui frappe surtout, c’est l’air triste qu’il affiche. L’expression du visage, la démarche du bonhomme, ses propos, rien décidément ne peut nous éclairer sur le fait que cette créature qui inspire avant tout la pitié est un grand capitaine d’industrie, patron dans plusieurs secteurs industriels. C’est clairement Marcel Dassault, fondateur des entreprises du même nom. Pierre Assouline raconte que «Carreidas est une caricature du génial constructeur des Mirage et des Mystère. Il lui a beaucoup emprunté : sa silhouette, son chapeau, son cache-col, son côté frileux... ». Hergé a sans aucun doute pensé à Dassault. Mais pas uniquement. Ainsi, ce qu’on sait de l’avionneur ne signale pas de pingrerie particulière. Cette pingrerie, Hergé l’emprunta plutôt à Jean Paul Getty, un célèbre magnat du pétrole. Alors que sa fortune approchait les 4 milliards de dollars, il avait équipé sa propriété de Los Angeles de téléphones à pièces, dont ses invités étaient priés de se servir. De même, en soulignant la phobie des microbes de Laszlo Carreidas qui l’empêche de serrer les mains (vraie phobie ou vrai manque de respect pour ses interlocuteurs ?), Hergé pensait-il sans doute davantage à Howard Hughes, dont la phobie de la contamination était telle qu’il a passé les dix dernières années de sa vie reclus et nu, dans des chambres d’hôtel, avec interdiction à quiconque d’y entrer, n’acceptant que la présence d’infirmiers... Avec son chapeau et son paletot froissé, son écharpe misérable et ses lunettes qui lui tombent sur le nez,? Laszlo Carreidas n’a rien de l’image classique du milliardaire.Mais Carreidas va surtout dévoiler l’ampleur de sa face obscure sous l’influence du sérum de vérité. Son nom renvoie au carré d'as qui d'ailleurs figure sur la queue de son avion supersonique. ",
    },
    {
        id: 31,
        nom: 'Chester',
        prenom: 'Robert',
        picture: '31.jpg',
        profession: 'Capitaine de marine marchande',
        personnage: "Marin et ami du capitaine Haddock ; ils se rencontrent fortuitement lors de leur escale à Akureyri en Islande. Grâce à son aide, l’Aurore est ravitaillé en mazout, alors même que la Golden Oil le lui a refusé pour faire triompher l’expédition concurrente du Peary !",
    },
    {
        id: 32,
        nom: 'De Hadoque',
        prenom: 'Francois',
        picture: '32.jpg',
        profession: 'Capitaine de marine du roi, commandant de vaisseau',
        personnage: "Personnage haut en couleur qui vécut dans la deuxième moitié du XVIIe siècle. Le vaisseau qu’il commandait en 1698 lors d’un retour des Antilles fut pris à l’abordage et pillé par le pirate Rackham le Rouge. Seul survivant de cet acte de brigandage, François de Hadoque réussit à échapper aux pirates en sabordant son propre navire. Il vécut deux ans sur une île des Antilles avant d’être recueilli par un vaisseau qui le ramena en Europe. En récompense de ses bons et loyaux services, Louis XIV fit don du château de Moulinsart au chevalier de Hadoque. L’acte de propriété signé par le roi Soleil est daté du 15 juillet 1695. Le chevalier légua à ses descendants le trésor de Rackham le Rouge qu’il cacha dans la crypte de son château à l’intérieur d’une sphère de pierre, aux pieds d’une statue de Saint Jean l’Evangéliste. Il est l’ancêtre du capitaine Haddock.",
    },
    {
        id: 33,
        nom: 'Chicklet',
        prenom: 'Ridley',
        picture: '33.jpg',
        profession: 'Agent de la General American Oil',
        personnage: "Cet intermédiaire véreux tente de soudoyer Tintin qui, alors colonel – aide de camp du général Alcazar, ne se laisse pas corrompre dans une affaire de concession pétrolière. Cette nouvelle concession située dans la région du Gran Chaco aux confins du San Theodoros et du Nuevo Rico risquerait d’entraîner un conflit armé entre ces deux pays. Chicklet se fait insistant pour annexer la partie convoitée qui se trouve dans le Nuevo Rico. Tintin balaye d’un revers de la main le pot-de-vin de 100.000 $. Tintin ne sait peut-être pas que dans certains pays la corruption est une condition sine qua non pour faire affaire. Ce refus de sa part lui coûtera presque la vie... Il échappera deux fois à la mort. Après une tentative d’attentat sur sa personne, c’est Pablo, le repenti, qui le sauve du peloton d’exécution. Chicklet, qui doit son nom à une marque de gomme à mâcher, fait une nouvelle apparition silencieuse dans L’Affaire Tournesol  (page 47, D2). Son look est soigné et il porte toujours un porte document.",
    },
    {
        id: 34,
        nom: 'Chiquito',
        prenom: 'Gall',
        picture: '34.jpg',
        profession: 'Dernier Incas, artiste de music-hall',
        personnage: "Il apparaît dans un numéro de lanceur de poignards au côté de Ramon Zarate, alias le général Alcazar. Ce travail n’est en réalité qu’une couverture. Il est en réalité chargé d’une fanatique mission : accomplir la vengeance de Rascar Capac dont la sépulture a été profanée. Chiquito est là pour se venger des sept explorateurs et endormir ces profanateurs à l’aide d’un gaz se trouvant dans les boules de cristal. Il participera à l’enlèvement du professeur Tournesol qui sera emmené à bord du cargo Pachacamac, destination le Pérou. Dans Le Temple du Soleil, Tintin le retrouve à bord du cargo ; Chiquito lui explique que Tournesol va être sacrifié. On le retrouve à la droite de l’Inca au cours de la cérémonie du sacrifice où il invoque le dieu du soleil sur l’autel du temple où faillirent bien rester nos amis.C'est lui qui détruit les statuettes envoutées des sept explorateurs qui servaient à les torturer à distance. Le nom « Chiquito » s’apparente à « Chiquitos » Indiens de Bolivie et de Brésil.",
    },
    {
        id: 35,
        nom: 'Cipacalouvishni',
        prenom: 'Deepali',
        picture: '35.jpg',
        profession: 'Fakir',
        personnage: "Son nom est un anagramme de « c’est pas ça li Vishnou ? ». Il n’est pas bouffon mais fakir. Il fait une apparition pour divertir Tintin et le maharadjah de Rawajpoutalah. C’est un homme qui ne manque pas de talent : marcher sur des tessons de bouteilles et percer son corps, non pas avec des aiguilles mais avec des couteaux ! Il joue à l’équilibriste, tête renversée, sur son lit à clous. Il est aussi doté d’incroyables dons de voyance et met en garde Tintin contre une menace qui pèse sur lui.",
    },
    {
        id: 36,
        nom: 'Coco',
        prenom: 'Yusuf',
        picture: '36.jpg',
        profession: 'Boy de Tintin',
        personnage: "Dans Tintin au Congo, il ne s’agit pas du perroquet qui apparaît dans Les Bijoux de la Castafiore. Il s’agit d’un jeune garçon qui accompagne notre héros tout au cours du récit congolais. « Boy » (littéralement garçon en anglais) est le terme pour désigner un domestique en Afrique francophone ! Un boy est chargé de tâches diverses qui vont de l’entretien de la maison à la préparation du repas. Dans Tintin au Congo, il sert aussi un peu de compagnon de voyage mais pas vraiment de guide ou d’interprète !  Il est assez pusillanime. Il fait deux apparitions dans le récit... dont une sera salvatrice pour Tintin.",
    },
    {
        id: 37,
        nom: 'Czarlitz',
        prenom: 'Dragan',
        picture: '37.jpg',
        profession: 'Photographe officiel de la cour de Syldavie',
        personnage: "Ce talentueux photographe n’apparaissant que furtivement dans Le Sceptre d’Ottokar, a pourtant joué un rôle très important dans l’affaire du complot contre Muskar XII, roi de Syldavie. En effet c’est grâce à lui et à son appareil photographique truqué que le sceptre a pu être dérobé. Sous le couvert d’une profession très officielle, Czarlitz conspirait contre le monarque syldave.",
    },
    {
        id: 38,
        nom: 'Dawson',
        prenom: 'J.M.',
        picture: '38.jpg',
        profession: 'Chef de police de la concession de Shanghai, trafiquant d\'armes',
        personnage: "Dawson, chef de police de la concession internationale de Shanghaï, intervient à plusieurs reprises dans Le Lotus bleu. Il est notamment « utilisé » par Gibbons et Mitsuhirato pour coincer Tintin qui devient un peu trop curieux à propos de leurs affaires. Dawson fait arrêter Tintin et il obtient même un mandat d’arrêt auprès de ses collègues chinois et envoie les Dupondt procéder à l'arrestation, qui échouera. Il apparaît en trafiquant d’armes dans Coke Stock, sous le nom de Dubreuil, travaillant pour le compte de Rastapopoulos. Homme sans scrupule, il n’hésite pas à utiliser la méthode forte pour tenter d’éliminer Tintin, cet empêcheur de tourner en rond ! (Placer une bombe par l’intermédiaire de Walter, dans l'avion Wadesdah-Beyrouth qui emmènent Tintin et le capitaine Haddock).",
    },
    {
        id: 39,
        nom: 'Diaz',
        prenom: 'Diego',
        picture: '39.jpg',
        profession: 'Colonel rétrogradé au rang de caporal de l\'arméesanthéodorienne',
        personnage: "Diaz incarne cet appareil étatique corrompu d’Amérique latine dirigé par une petite ploutocratie militaire où l’armée symbolise l’autorité dictatoriale. Pas surprenant dès lors de voir une pléthore d’officiers généraux ou supérieurs dans l'armée du San Théodoros pour récompenser les amis. Diaz jalouse Tintin, nommé colonel et aide de camp du général Alcazar et se voit rétrogradé au rang de caporal après s’être rebellé contre cette nomination. Diaz outragé et brisé rejoint l’opposition où il participe activement à fomenter des attentats contre ce cher général Alcazar ! Après l’arrestation de Tintin pour trahison, Diaz retrouve son grade de colonel mais en vain puisqu’il meurt déchiré par sa propre bombe... Cette case est plus qu’unique dans la bande dessinée car elle laisse entrevoir les pires atrocités du vingtième et du vingt et unième siècle.",
    },
    {
        id: 40,
        nom: 'Les Dupont',
        prenom: 'Marius & Augustin',
        picture: '40.jpg',
        profession: 'Agent de police',
        personnage: "Si les catastrophes vous font peur, surtout ne lisez pas ce qui suit ! Voici le portrait de deux experts en bouleversements, désordres, gaffes, chambardements, troubles, chamboulements, perturbations, confusions, malentendus et méprises ! Présents dans 20 des 24 albums Tintin, héros d'un feuilleton, dont ils furent les vedettes, et protagonistes de deux pièces de théâtre, les Dupondt jouent plus que les utilités : ils sont un maillon indispensable dans la saga inventée par Hergé ! C'est en 1932 que deux policiers veulent arrêter Tintin aux prises avec les péripéties des aventures suscitées par Les Cigares du Pharaon. Ils portent alors seulement un nom de code : X33 et X33bis. Confiez-leur une mission, ils embrouillent une situation déjà compliquée. S'ils doivent respecter une certaine discrétion, on ne voit qu'eux. Courageux, mais pas téméraires, il leur arrive d'avoir peur de leur ombre - ou de leur image passée aux rayons X, comme dans Objectif Lune ! Le père de Hergé, Alexis Remi, avait un frère jumeau, Léon Remi. De vrais jumeaux : tous deux portaient la moustache et s'habillaient de manière identique. À chaque sortie, ils ne manquaient pas de porter un canotier ou un chapeau melon. Sans oublier une canne ou un parapluie ! Si Alexis et Léon Remi étaient frères, les Dupondt ne le sont pas. L'un s'appelle Dupond ; l'autre, Dupont. S'ils étaient frères, leurs noms s'orthographieraient de manière identique. Jumeaux ? Non. Sosies, oui ! Pourquoi un habit aussi identifiable ? À cette époque, les inspecteurs de police recevaient un maigre dédommagement pour leur « habit de travail », qu'ils devaient se procurer eux-mêmes. Le solide tissu noir étant le moins cher, la plupart d'entre eux adoptèrent le costume de cette couleur, ainsi que les inusables bottines à clous. Quant à la moustache... Cela vous posait un homme ! Il vous suffit de voir l'Agent 15, apparu dans les gags de Quick et Flupke en 1930, deux ans avant les Dupondt. À n'en pas douter, sa moustache est l'ancêtre de celles de nos deux limiers. ... Et cependant, ils y mettent tant de bonne volonté ! L'ennui avec les Dupondt, c'est que ça se remarque quand ils veulent passer inaperçus. Au travers des déguisements des Dupondt, Hergé se moquait gentiment des idées toutes faites que la plupart de ses contemporains entretenaient sur les pays lointains. ",
        personnage_suite: "Si vous cherchez un florilège de malentendus, ouvrez Le Temple du Soleil. Alors qu'ils recherchent Tintin, Tournesol et Haddock, disparus au Pérou, les Dupondt effectuent à peu près le tour du monde pour les retrouver. Leur secret ? Mal interpréter les indices à leur disposition. Pas courageux, les Dupondt ? Qui oserait affirmer une chose pareille, lorsque l'on additionne les cascades qu'ils ont accomplies en 20 albums ? S'ils partent vers la Lune, c'est parce qu'ils se sont endormis dans la fusée spatiale. S'ils battent le record de vitesse en descente d'escalier, c'est parce qu'ils ont raté la première marche. S'ils effectuent des cascades aériennes, c'est parce qu'ils ont oublié de serrer leur ceinture de sécurité."
    },
    {
        id: 41,
        nom: 'Endadine',
        prenom: 'Akass',
        picture: '41.jpg',
        profession: 'Escroc',
        personnage: "Un gourou spirituel qui dispose d’un charisme hors norme et fait tomber son audience sous son charme. Endaddine Akass est en fait un mage stratégique ou un filou sournois qui a quelques squelettes dans son placard.",
    },
    {
        id: 42,
        nom: 'Euclide',
        prenom: 'R.W.',
        picture: '42.jpg',
        profession: 'Professeur, historien',
        personnage: "Ce professeur distrait fait une apparition tout à fait surréaliste et remarquable même si furtive. Il apparaît dans un double « strip » comme pour annoncer la venue de Tournesol. Sa distraction prend des proportions qui dépassent l’entendement ! Monsieur Euclide sort vêtu d’une robe de chambre ornée de fourrure ainsi qu’il sied à une personne de son rang.  Il avait cru prendre son parapluie au design intemporel très british…mais de nouveau son étourderie lui joue des tours ! Le point culminant de son apparition est sa rencontre avec un perroquet en haut d’un réverbère ! Le dialogue qui en découle est un bijou à la simplicité trompeuse... Avec Hergé, la conversation devient un art !",
    },
    {
        id: 43,
        nom: 'Violette',
        prenom: 'Ernestine',
        picture: '43.jpg',
        profession: 'Servante, bonne, gardienne d\'immeuble',
        personnage: "Ernestine personnifie la bonté même! On la voit mignarder le professeur Euclide et l’entourer de toutes les attentions affectueuses !",
    },
    {
        id: 44,
        nom: 'Su',
        prenom: 'Fang Se-Yeng',
        picture: '44.jpg',
        profession: 'professeur de médecine',
        personnage: "Fang Se-Yeng connu pour ses ouvrages sur la folie fait la Une des actualités suite à son retour à Shanghai après un long voyage aux Etats-Unis. Pour Tintin c’est l’homme de la situation qui peut sauver Didi. Tintin arrivera trop tard. Le professeur est enlevé par des trafiquants au service de Rastapopoulos pour empêcher toute guérison de Didi. Le professeur est détenu prisonnier au Lotus bleu. Il sera libéré grâce à Tintin et les Fils du Dragon. Il guérit Didi et toutes les autres victimes du poison. Il participe au banquet organisé en l’honneur de Tintin avant son départ pour l’Europe.",
    },
    {
        id: 45,
        nom: 'Foudre bénie',
        prenom: 'Tchong',
        picture: '45.jpg',
        profession: 'moine tibétain',
        personnage: "La particularité originale de Foudre Bénie, c’est qu’il lévite lors de ses visions et qu’il n’en a ensuite aucun souvenir. Un détail qui l’exonère d’être un escroc qui utiliserait ses « dons » pour en tirer profit, comme l’ont fait de nombreux illusionnistes pour faire croire à la capacité de s’affranchir de la loi de la pesanteur. Foudre Bénie n’est pas un personnage envahissant : il apparaît dans dix-sept cases en tout. Dix-sept ? Ce serait sans compter une dernière apparition un peu mystérieuse et cryptique, qui échappe au lecteur trop rapide. À la dernière page du récit, il ne distingue pas nécessairement qu’à la première case, au-dessus des murs de la lamaserie, un moine prend son envol. Certes, c’est presque indiscernable. Mais c’est certain : c’est la quatrième vision de Foudre Bénie…",
    },
    {
        id: 46,
        nom: 'Gibbons',
        prenom: 'Harold',
        picture: '46.jpg',
        profession: 'homme de confiance de Al Capone',
        personnage: "À ne pas confondre avec Gibbons qui apparaît dans Le Lotus bleu, il est chargé par A.C. (Al Capone « himself ») d’éliminer Tintin. Pour ce faire il utilise un homme de paille Tom. Son nom renvoie au mot vernaculaire « gibbon » qui désigne plusieurs espèces de primates ! Il est mêlé aux activités de Al Capone de trafic de diamants. Al Capone en Afrique est une invention d’Hergé !",
    },
    {
        id: 47,
        nom: 'Le Goffic',
        prenom: 'George',
        picture: '47.jpg',
        profession: 'Commandant du paquebot Ville de Lyon',
        personnage: "Il est le « capitaine » du navire Ville de Lyon et délègue ses responsabilités de quart aux autres officiers et stewards. Il est présent en passerelle pour les départs et les arrivées de port. On le voit lorsque le paquebot entre en rade de Las Dopicos. Il est présent lors de l’arrestation des deux passagers Ramon Bada et Alonzo Perez.",
    },
    {
        id: 48,
        nom: 'Grand Precieux',
        prenom: 'Jaime',
        picture: '48.jpg',
        profession: 'Chef spirituel du monastère de Khor-Biyong',
        personnage: "Ce digne et impassible chef religieux au visage impénétrable représente dans cette aventure tout le mysticisme et les secrets du Tibet traditionnel. Le langage du Grand Précieux est particulièrement soigné ; on admirera ainsi les termes inattendus pour s’adresser à nos amis : Cœur Pur, Tonnerre Grondant et Neige du Matin. La présence du capitaine Haddock auprès du Grand Précieux, absolument dépaysé dans ce cadre étranger, représente l’incompréhension totale de la civilisation occidentale envers le Tibet mystérieux. Haddock qui renverse le plateau, s’étonne de la calvitie volontaire des moines tibétains et souffle dans les trompes sacrées, est pourtant plein de respect pour le Grand Précieux qu’il qualifie avec déférence d’une série de termes malheureusement mal choisis : Grand Sachem, Grand Vizir, Grand Mufti, Grand Mogol, Grand Bazar, Grand Trésor, Grand Turc.",
    },
    {
        id: 49,
        nom: 'Halambique',
        prenom: 'Nestor',
        picture: '49.jpg',
        profession: 'Expert en sigillographie, professeur',
        personnage: "Le professeur Halambique est un expert en sigillographie (étude des sceaux). Nestor a été kidnappé et son identité a été usurpée par son frère jumeau (Alfred). Ce dernier se présente comme Nestor dans le cadre du complot visant à voler le sceptre d'Ottokar IV.",
    },
    {
        id: 50,
        nom: 'Wagner',
        prenom: 'Igor',
        picture: '50.jpg',
        profession: 'Musicien, pianiste',
        personnage: "À cause de ses obligations professionnelles, Igor Wagner vit dans le sillage de Bianca Castafiore dont il est l’accompagnateur exclusif. Ce petit homme discret et taciturne, constamment éclipsé par la personnalité démesurée de la bruyante cantatrice, mène pourtant une double vie. Wagner est joueur ! La passion du jeu l’amène dans Les Bijoux de la Castafiore a avoir recours à un subterfuge pour aller téléphoner ses pronostics durant ses heures de travail. Sa patronne, d’une étonnante naïveté, ne découvrira jamais qu’un magnétophone permet à son pianiste de prendre quelques heures de repos journalier. La tournée au San-Théodoros (Tintin et les Picaros) de Bianca Castafiore faillit mal tourné pour le petit pianiste et la camériste Irma qui faillirent passer par le peloton d’exécution.",
    },
    {
        id: 51,
        nom: 'Jimenez',
        prenom: 'Carlos',
        picture: '51.jpg',
        profession: 'Colonel de l\'armée du san-Théodoros, militaire',
        personnage: "Comme pour le colonel Diaz, Jimenez incarne cet appareil étatique corrompu d’Amérique latine dirigé par une petite ploutocratie militaire où l’armée symbolise l’autorité dictatoriale. Pas surprenant dès lors de voir une pléthore d’officiers généraux ou supérieurs dans l'armée du San Théodoros pour récompenser les amis. Jimenez est chargé de réceptionner les bandits Bada et Perez sur le paquebot Ville-de-Lyon. Il participe aussi à la machination qui conduira Tintin au peloton d’exécution.",
    },
    {
        id: 52,
        nom: 'Juanitos',
        prenom: 'Pedro',
        picture: '52.jpg',
        profession: 'Colonel de l\'armée du san-Théodoros, militaire',
        personnage: "Enième colonel de l’armée san-théodorienne, il reçoit l’ordre d’arrêter Tintin après les intrigues secrètes de M.Chicklet.",
    },
    {
        id: 53,
        nom: 'Brancion',
        prenom: 'Jules',
        picture: '53.jpg',
        profession: 'Gardien du musée ethnographique',
        personnage: "Personnage très secondaire certes mais il apparaît dans l’incipit du récit dans une sorte d’invitatoire et par là il est inoubliable. Son uniforme vert claque dans la première page de l’album.  Il est celui qui découvre la disparition du fétiche et est le premier à alerter le conservateur. Témoin privilégié de la scène survenue au musée, il confie à la presse ses premières impressions et son intime conviction : c’est de la sorcellerie ! ",
    },
    {
        id: 54,
        nom: 'Kaloma',
        prenom: 'Kall',
        picture: '54.jpg',
        profession: 'Chef de la tribu des Arumbayas',
        personnage: "Kaloma, en sa qualité de chef, symbolise la culture et la tradition orale qui ne peut être dissociée de la tribu ! C’est par son intermédiaire et avec l’aide Ridgewell, qui sert de traducteur, que Tintin peut reconstituer les fragments de l’histoire du fétiche. Même si Kaloma n’apparaît pas si vieux, il est l’exemple de ces vieillards ou sages, recueils vivant de cette culture orale mais aussi éphémères :  Quand un vieillard meurt c’est une bibliothèque qui s’envole en fumée . On retrouve Kaloma dans Tintin et les Picaros. Tintin et ses amis font une halte dans le village des Arumbayas.",
    },
    {
        id: 55,
        nom: 'Kaviarovitch',
        prenom: 'Mirko',
        picture: '55.jpg',
        profession: 'Agent secret',
        personnage: "Ce curieux moustachu à lavallière qui fait une apparition brutale dans l’appartement de Tintin à la page 7 du Sceptre d’Ottokar est chargé par les services secrets de son pays de surveiller les organisations syldaves à l’étranger. Ainsi, sous les traits d’un artiste peintre, ressortissant balkanique, Kaviarovitch est sur la piste des conspirateurs qui tentent de renverser la monarchie syldave au profit de la Bordurie. Malencontreusement frappé d’amnésie, ce pittoresque moustachu ne peut dévoiler à Tintin le complot qui se prépare avec l’aide du faux professeur Halambique. Un rapport précis établi cet imposteur concernant les activités de l’agent secret syldave sera découvert après l’arrestation d’Halambique. Son nom est inspiré du mot persan khaviar élaboré à partir des œufs d’esturgeon.",
    },
    {
        id: 56,
        nom: 'Haddock',
        prenom: 'Archibald',
        picture: '56.jpg',
        profession: 'Capitaine de marine',
        personnage: "Haddock est assurément le plus aimé des personnages des Aventures de Tintin. Son tempérament emporté, ses coups de gueule, ses faiblesses, son côté tantôt maladroit, tantôt courageux font de ce personnage un “véritable cœur qui bat”, nous dirons même plus, une palpitation d'âme.Le capitaine Haddock apparaît pour la première fois le 2 janvier 1941, à la page 4 du supplément Le Soir Jeunesse. Sa première rencontre, historique, avec Tintin aura lieu une semaine plus tard, le 9 janvier 1941. Remarquons qu’un personnage de fiction n’a pas d'âge... Pourtant, ne cherche-t-on pas, en vain, celui du capitaine ? Comme Tintin est l’archétype du reporter, Haddock est celui du marin. Notre homme est même capitaine au long cours. Bien qu'à ses débuts il fit plutôt figure d’“épave”. Plus tard, le capitaine Haddock devient rentier, vivant dans le château ayant appartenu à ses ancêtres. Mais, même affublé des habits d'un noblion parvenu, il restera toujours le vieux loup de mer qu’on adore. En bref, un officier et un gentleman... On lui reconnaît volontiers un mauvais caractère, mais quel bon cœur ! Il est d’ailleurs toujours prêt à aider les faibles. Comme Tintin. Comme un scout... de mer... « Mélange composite de rugosité et de tendresse, soupe au lait au cœur d’artichaut, notre vieux loup de mer a fait depuis 1941 les délices de générations de lecteurs. » Sans aucun doute, nous nous trouvons face à un héros prêt à se sacrifier pour sauver la vie de son jeune ami. L’homme est courageux, mais aussi maladroit que les Dupond(t) et rivalise avec les célèbres faux jumeaux dans le domaine des catastrophes et accidents en tous genres. On y retrouve toute la joyeuse famille de Tintin bien sûr, mais n’oublions pas « ce vieux Chester », avec qui il a navigué pendant plus de vingt ans et avec qui il exécute un incroyable rite d'initiés.",
    },
    {
        id: 57,
        nom: 'Alcazar',
        prenom: 'Fernando',
        picture: '57.jpg',
        profession: 'Général, commandant de troupe révolutionnaire',
        personnage: "Alcazar est un mot espagnol désignant un palais fortifié. Comme les Alcazars de Séville et de Tolède, ces palais ont été construits lors de la conquête de l'Espagne par les Maures, population d'origine berbère. Officier du plus haut grade - général - commandant les troupes révolutionnaires en place dirigée par un autre général Tapioca. La république du San Theodoros est le terrain de jeu de Alcazar et Tapicoa. À la suite de revers de fortune, le général Alcazar s'est illustré comme lanceur de couteaux dans les plus grands music-halls sous le nom de Ramon Zarate. À part le jeu de la révolution, Alcazar joue aux échecs et fume le cigare. L'aventure de Tintin L'Oreille cassée, où Tintin rencontre pour la première fois Alcazar, s'inspire d'un conflit sanglant qui a opposé au cours des années trente la Bolivie et le Paraguay qui se disputaient un territoire : le Gran Chaco. Cette guerre fut baptisée la Guerre du Pétrole. Les Gringos (Standard Oil américaine) et autres multinationales occidentales (Royal Dutch Shell) étaient impliquées dans ce conflit. Mais le vrai motif de la guerre était le dessin de la Bolivie de se ménager un meilleur passage à la rivière Paraguay. Le Gran Chaco est devenu sous le coup de crayon d'Hergé le Gran Chapo. Le San Théodoros reviendra à la une dans Tintin et les Picaros où Hergé caricaturera l'ingérence des puissances commerciales dans les affaires politiques des pays du tiers monde. (Michael Farr Tintin, Le rêve et la réalité, Ed. p.195). Peggy, bien que cela ne soit pas dit dans l'album, est la fille du marchand d'armes Basil Bazaroff qui apparaît dans L'Oreille cassée. Bazaroff est le portrait caricatural du marchand d'armes Sir Basil Zaharoff qui fit fortune dans l'industrie de la mort pendant et après la première guerre mondiale. (Michael Farr Tintin, le rêve et la réalité, Ed. Moulinsart, p.62). « L'ambiguïté d'Alcazar est celle, tout simplement, de l'homme politique. Il est l'ami ou l'ennemi de Tintin suivant que Tintin sert sa cause ou est un obstacle à celle-ci. La raison d'État, ou, plus vulgairement, l'ambition personnelle, voilà ce qui dicte le comportement du Général...» (Numa Sadoul, Tintin et Moi entretiens avec Hergé, Ed. Casterman, p.205). ",
    },
    {
        id: 58,
        nom: 'Bergamotte',
        prenom: 'Hyppolite',
        picture: '58.jpg',
        profession: 'Professeur, scientifique, savant',
        personnage: "Bergamotte (Hyppolite). La bergamote est le nom d'une variété d'orange dont l'essence est utilisée en confiserie et en parfumerie. Américaniste, c'est-à-dire, selon le Petit Robert, spécialiste (ethnologue, archéologue, linguiste) du continent américain et de ses civilisations autochtones précolombiennes et indiennes. Bergamotte a notamment rédigé un mémoire sur les sciences occultes de l'ancien Pérou. Hergé se serait inspiré pour créer Bergamotte de l'illustre Jean Capart, égyptologue, né à Bruxelles le 21 février 1877. Il a été chargé de cours à de nombreux instituts ou universités et en 1911, fut le conservateur en chef des Musées Royaux d'Art de l'Histoire de Bruxelles. Il est à noter que Jean Capart a voyagé en Amérique du Sud en 1936 et à l'occasion de visites de musées s'est intéressé à des collections sur les Indiens. Ses périples sont relatés dans un livre rédigé par un membre de sa famille, A-M. Brasseur Capart, intitulé Jean Capart ou le rêve comblé de l'Egyptologie. Hergé lui-même écrivait le 5 février 1975 à A-M. Brasseur Capart pour la féliciter pour son ouvrage. Bergamotte est le dernier des sept (allusion aux six autres membres de l'expédition). Échappera-t-il au sort jeté sur les différents membres de l'expédition ethnographique Sanders-Hardmuth par un étrange  indien fanatique, résolu à punir les audacieux qui ont profané la sépulture du roi inca Rascar Capac Bergamotte est un compagnon d’études de Tournesol. Même si ce dernier ne s’est jamais profilé comme un américaniste. Il semble également annoncer le Doktor Grossgrabenstein du « Mystère de la grande Pyramide » (Black et Mortimer — Edgar Jacobs).",
    },
    {
        id: 59,
        nom: 'Tryphon',
        prenom: 'Tournesol',
        picture: '59.jpg',
        profession: 'Professeur, archéologue, ethnologue',
        personnage: "Inventeur de génie, étourdi, sourd jusqu'au ridicule, le professeur Tournesol apparaît pour la première fois en 1944 avec la publication du Trésor de Rackham le Rouge. Sa présence sera assurée, particulièrement parce que, à la fin du récit, son argent permet au capitaine Haddock de faire l'acquisition de la demeure de ses ancêtres, le château de Moulinsart. Les espions de la fusée lunaire l'ont surnommé le Mammouth. Peut-être font-ils ainsi allusion au caractère massif... de son intelligence ? On ne sait quasiment rien de la famille de Tryphon Tournesol. La seule indication qu'il livre à ce sujet s'énonce en forme négative : il n'a jamais eu de sœur ! Très distrait, affligé de surdité, intuitif et sentimental à l'extrême, il établit avec le réel, au moyen de son pendule, des connexions inattendues, tantôt complètement loufoques. Il présente tous les caractères du scientifique décidé à faire prévaloir ses idées: une assurance sans faille, une obstination sans limites et une pointe d'irritabilité. La surdité de Tournesol est une source inépuisable de quiproquos qui fait de lui un personnage comique. Comme de nombreuses personnes à l'ouïe défaillante, il refuse de l'admettre, concédant qu'il est peut-être un peu dur d'oreille. Cette surdité aurait été inspirée par l'avocat Paul Eydt, collaborateur au  Vingtième Siècle , dont l'handicap était source de plaisanteries à la rédaction. D'abord fin bricoleur, puis inventeur astucieux, Tournesol ira jusqu'à concevoir la fusée atomique qui mènera Tintin sur la Lune. Tournesol est également chimiste et il ne manque pas de talent. Il mit par exemple au point l'antidote au N.14 du Dr Müller dans Tintin au pays de l'or noir. Le professeur est aussi un passionné de la radiesthésie, une croyance selon laquelle il serait possible de découvrir des sources, retrouver un objet perdu ou une personne disparue ou encore d'établir un diagnostic médical. Il emporte d'ailleurs toujours son pendule avec lui.",
    },
    {
        id: 60,
        nom: 'Loiseau',
        prenom: 'Guillaume & Maxime',
        picture: '60.jpg',
        profession: 'Antiquaire véreux',
        personnage: "Ils occupent le château de Moulinsart. Ils sont prêts à tout (kidnapping, meutre, vol, etc.) pour récupérer les deux parchemins manquants qui les mèneraient au trésor de Rackham le Rouge.",
    },
    {
        id: 61,
        nom: 'Wings',
        prenom: 'Gordon',
        picture: '61.jpg',
        profession: 'Pilote d\'avion',
        personnage: "Le major Wings est un as du pilotage difficile. Le capitaine Haddock qui est le commandant du navire L’Aurore est le premier à le reconnaître. L’amerrissage en mer polaire entre une forêt d’icebergs n’est pas, il est vrai, une chose facile. Il aime les animaux et a fait acte de bravoure en venant au secours de Milou en difficulté sur une des ailes de l’hydravion. Il n’hésite pas non plus à risquer sa vie pour poser son avion dans les remous violents d’une mer démontée causés par l’aérolithe pour venir en aide à Tintin.",
    },
    {
        id: 62,
        nom: 'Mac Duff',
        prenom: 'Jimmy',
        picture: '62.jpg',
        profession: 'Trafiquant d\'animaux',
        personnage: "Il se présente comme le fournisseur (pas de la Cour) des plus grands zoos d’Europe. Il apparaît juste le temps d’un strip ! Difficile de se faire une idée de ce personnage de seconde zone.  Il inspire la crainte et il a une mine plutôt patibulaire. Il est le propriétaire du léopard qui fait une apparition hautement symbolique dans la version noir et blanc de Tintin au Congo ; il y a cette scène de la classe riche d’enseignement où Tintin déclare: « La Belgique, est-ce qu’on appelle... un léopard ». Or pour un congolais, un léopard inspire la crainte ou la menace.",
    },
    {
        id: 63,
        nom: 'Rawhajpoutalah',
        prenom: 'Ahaan',
        picture: '63.jpg',
        profession: 'Maradjah',
        personnage: "Un souverain pétri de bonnes intentions, mais néanmoins naïf, restant impuissant face à la montée des périls et aveugle aux conseillers félons qui l’entourent ? Le maharadjah de Rawhajpoutalah est un homme simple. Quand Tintin le rencontre, il porte une tunique traditionnelle à manches longues et se coiffe d’un turban sans aucune forme d’ostentation. C’est seulement lors des sorties et des réceptions officielles, qu’il porte un élégant costume de soie sur mesure, rehaussé de bijoux sertis de pierres précieuses. Le territoire du Rawhajpoutalah se situe à proximité de New Delhi, dans le nord-est de l’Inde, près des frontières du Népal et du Tibet.",
    },
    {
        id: 64,
        nom: 'Milou',
        prenom: 'Neige blanche du matin',
        picture: '64.jpg',
        profession: 'animal de compagnie de Tintin',
        personnage: "Milou est un Fox-terrier à poil dur d'une blancheur atypique. Si Milou laisse apparaître de temps en temps un goût pour l'aventure, il penche plutôt pour une vie pépère et ne comprend pas toujours les élans à la Don Quichotte de son maître. Les moines tibétains baptisèrent Neige du matin le compagnon de Tintin. Milou est pour son maître un interlocuteur, il converse avec lui. Non qu'il soit un chien parlant, Milou est le plus ordinaire, le plus normal, le plus canin des chiens. Bien que fort loquace, il parle chien, et c'est ainsi seulement que le perçoit Tintin. Mais le dialogue se situe au niveau de l'instinct, d'une télépathie secrète : entre Milou et son ami, c'est une question d'ondes mystérieuses, la complicité du silence. (Galerie de Portraits dans Numa Sadoul, Tintin et Moi, p.240). Sa générosité et sa fidélité le contraignent à sortir de l'oisiveté et à suivre bon gré malgré Tintin dans ses aventures. Son flair, sa fidélité et son courage permettront souvent à Tintin de se tirer d'affaires et d'échapper au danger. Parfois Milou succombe à certaines tentations et cède à la gourmandise, à la curiosité ou tout simplement à son instinct d'animal qui lui posent des dilemmes presque cornéliens. Mais très vite son sens du courage l'emporte et il revient dans le droit chemin pour aider son maître. En bien des points, le fidèle compagnon ressemble au capitaine Haddock : râleur, bavard, irritable et têtu, vantard, gaffeur et malchanceux, il y a du capitaine en ce chien difficile. (Galerie de Portraits dans Numa Sadoul, Tintin et Moi, p.240). L'apparition du capitaine Haddock dans les aventures de Tintin contribuera à diminuer progressivement la loquacité de Milou et son rôle complice.",
    },
    {
        id: 65,
        nom: 'Hirado',
        prenom: 'Mitsuhirato',
        picture: '65.jpg',
        profession: 'Fripier, commerçant, agent secret, espion, brigand',
        personnage: "Mitsuhirato, est un rude coquin. L’homme est un des cerveaux du crime actifs à Shanghai. Il agit sous la tranquille apparence d’un commerçant en bonneterie et en soierie, activité prisée par ses compatriotes en Chine. Mitsuhirato soigne les détails jusqu’à adopter une adresse qui se voudrait rassurante, puisqu’il loge…rue de la Tranquillité. Son style est fleuri : il veut « contempler le glorieux et vertueux visage » de Tintin. Mais derrière ce masque se cache en fait tout autre chose. Non seulement Mitsuhirato fait partie de la bande de Rastapopoulos, qui trafique l’opium entre Orient et Europe, mais il agit aussi en sous-main à la tête d’une cinquième colonne introduite en Chine afin de provoquer des incidents qui justifieraient une plus large intervention des troupes japonaises.",
    },
    {
        id: 66,
        nom: 'Mogador',
        prenom: 'Enrique',
        picture: '66.jpg',
        profession: 'Général et chef d\'Etat du Nuevo Rico',
        personnage: "Il symbolise cette militarisation de la société latino-américaine qui donne naissance au phénomène de Caudillo : leader politique souvent issu de l’armée qui prend le pouvoir dans certaines régions après l’indépendance des pays de l’Amérique latine. Le général Mogador est le dirigeant du Nuevo Rico et rencontre Basil Bazaroff pour l’achat de matériel militaire. « Mogador » est l'ancien nom de la ville d'Essaouira au Maroc.",
    },
    {
        id: 67,
        nom: 'Ben Kalish Ezab',
        prenom: 'Mohammed',
        picture: '67.jpg',
        profession: 'Emir du Khemed',
        personnage: "Signe particulier : Dans son élégante tenue traditionnelle - dishdasha blanche, bisht sombre et keffieh -, lunettes rondes et barbiche noire, Ben Kalish Ezab est déterminé à éliminer ses ennemis. Dans la galerie des personnages créés par Hergé, Mohammed Ben Kalish Ezab ne passe pas inaperçu. Outre sa tenue vestimentaire qui évoque déjà dans nos esprits tout l’exotisme du Moyen-Orient, il se distingue également par un comportement qui passe par toutes les couleurs de l’arc-en-ciel : colères froides, exubérance de paroles, sensiblerie larmoyante, tout est dans la démesure et la flamboyance. Homme des extrêmes, il rejoint son fils Abdallah dans la catégorie des personnages « toujours au bord de la crise de nerfs ». Bien sûr, on lui connaît des périodes de rémission, mais elles sont le plus souvent éphémères et débouchent inévitablement sur de nouvelles extravagances verbales et comportementales. La présence de Tintin et du capitaine Haddock semble avoir un effet apaisant sur cette personnalité hors norme. C’est compter sans Milou qui va involontairement déclencher une belle pagaille dans le repaire de l’émir. Mohammed Ben Kalish Ezab se met en marche, le doigt inquisiteur...",
    },
    {
        id: 68,
        nom: 'Muganga',
        prenom: 'Bougangbou',
        picture: '68.jpg',
        profession: 'Sorcier de la tribu des Babaorom',
        personnage: "Son nom veut dire littéralement en swahili « l’homme qui soigne ». Depuis la venue de Tintin, il craint pour son poste ou sa position dans la tribu des Babaoro’m. Décidément ce Tintin, ce petit Blanc, lui fait de l’ombre ! Il va faire un pacte avec le diable, Tom un de la bande de A.C. L’originalité de sa parure ne tient pas à une qualité locale mais plus à son côté ridicule ! Ce bouffon sorcier qu’Hergé dessine avec une casserole sur la tête est inspiré d’une carte postale reproduisant un chef de village de la région de Lukénie ! Peau de léopard à la taille, une pipe africaine à la main, ce sorcier n’en demeure pas moins crédible. Il est membre de la société secrète des Aniotas dite aussi « hommes-léopards ». Les Aniotas sont membres d'une société secrète africaine criminelle dans la tendance animiste. Muganga manque d'être étouffé par un boa et ne doit sa vie qu'à l'intervention de Tintin. Il renonce alors à se venger.",
    },
    {
        id: 69,
        nom: 'Muskar',
        prenom: 'Piotr',
        picture: '69.jpg',
        profession: 'Roi de Syldavie',
        personnage: "Quel pays réel a inspiré la Syldavie et quel souverain est le modèle de Muskar XII ? Il n’y a pas de réponse unique. Graphiquement, il n’y a pas de doute que Muskar XII ressemble comme un cousin peu éloigné à Zog Ier, encore roi d’Albanie (1928 à 1939) pour quelques semaines quand Hergé commence à dessiner Le Sceptre d’Ottokar, en août 1938. Hergé lui-même reconnut que l’annexion de l’Albanie par l’Italie fut une source d’inspiration : le 12 juin 1939, il écrit une lettre à Charles Lesne (son éditeur chez Casterman) où il affirme que « La Syldavie, c’est l’Albanie. Il se prépare une annexion en règle ».",
    },
    {
        id: 70,
        nom: 'Da Figueira',
        prenom: 'Oliveira',
        picture: '70.jpg',
        profession: 'Commerçant',
        personnage: "Le senhor Oliveira da Figueira vit ordinairement à Lisbonne, d’après les affirmations du capitaine du boutre qui recueille Tintin lors d’une tempête en mer Rouge, au début des Cigares du Pharaon. Son prénom est un nom fréquent au Portugal et Figueira désigne une ville du centre du pays. On découvre vite sa principale caractéristique : c’est un vendeur qui sort de l’ordinaire. À peine débarqué sur la côte arabe, il utilise les techniques modernes du marketing comme les annonces sonores ou la promesse de primes pour mieux attirer les populations locales, qui lui ont donné le sobriquet de « Blanc-qui-vend-tout ». C’est le camelot magnifique, le bonimenteur ultime, capable de vendre les objets les plus incongrus tout en donnant à sa victime le sentiment de faire une bonne affaire. Sa moustache en croc à la Dali révèle le soin particulier qu’il apporte à la séduction. Oliveira est un commerçant aisé, il a l’embonpoint prospère. Si, au fil des aventures, Oliveira da Figueira est devenu un proche de Tintin, c’est aussi un rusé coquin.",
    },
    {
        id: 71,
        nom: 'L\Inca',
        prenom: 'Milagros',
        picture: '71.jpg',
        profession: 'Sapa Inca dirigeant de l\'empire Inca',
        personnage: "L’Inca doit au simple article défini qui précède son titre de signifier qu’il est, unique, à la tête de sa civilisation et de son empire. « Sapa Inca », en quechua, signifie « inca unique », comme « Intip churin » signifie « fils du soleil », précisément les deux termes utilisés par Hergé pour désigner ce personnage. L’Inca apparaît comme un personnage au pouvoir sans limites. Pour éviter de voir divulguée l’existence du Temple du Soleil au monde extérieur, il n’a pas d’autre voie que de condamner les étrangers au bûcher.",
    },
    {
        id: 72,
        nom: 'Le Rouge',
        prenom: 'Rackham',
        picture: '72.jpg',
        profession: 'Pirate',
        personnage: "Ce cruel personnage écuma la mer des Antilles vers la fin du XVIIe siècle. Il dut abandonner son navire qui battait le fameux pavillon noir ne pouvant échapper aux tirs fatals des canons de la Licorne et prit d’assaut le vaisseau commandé par le chevalier François de Hadoque. Possesseur d’un immense trésor («...Dix fois de quoi payer la rançon d’un roi » !). Ce qui est certain, c’est que ce trésor sera à coup sûr très convoité par le Chevalier de Hadoque suite à son combat singulier avec le pirate qui sera fatal à ce dernier ! Signe particulier : son haleine empeste parfois l’alcool. Personnalité : Très rancunier et particulièrement cruel.",
    },
    {
        id: 73,
        nom: 'Capac',
        prenom: 'Rascar',
        picture: '73.jpg',
        profession: 'Guerrier',
        personnage: "L'Inca Rascar Capac est inspiré des noms des Incas qui ont régné au Pérou comme Manco-Capac, Mayta-Capac ou Huascar. Il apparaît dans l'album Les 7 Boules de cristal. L'Inca Rascar Capac n'a jamais existé et a été imaginé par Hergé. La momie a été découverte par l'expédition Sanders-Hardmuth dont il est fait mention au tout début de l'album. La momie de l'Inca Rascar Capac est coiffée du borla ou diadème royal en or massif. Inca ou seigneur était le titre que portèrent, au Pérou, les souverains dont la conquête espagnole détruisit la dynastie. L'Inca est considéré unanimement comme un envoyé céleste. Son pouvoir n'avait aucune limite, mais la tradition rapporte qu'il en faisait un excellent usage, toujours dans l'intérêt de son peuple. Au cours de ses conquêtes, il préférait les négociations à la guerre, se montrait clément dans la victoire. L'administration reposait sur un principe fort simple, appliqué par d'innombrables fonctionnaires contrôlés par une véritable armée d'inspecteurs vigilants. Le pays était divisé en quatre provinces, gouvernées chacune par un parent de l'Inca. La population était répartie en groupes de dix hommes ou décuries. L'un de ces hommes, désigné par le gouvernement, commandait aux neuf autres. Il leur devait toute l'assistance sociale possible. Cinq de ces décuries étaient placées sous les ordres d'un décurion. Dix décuries avaient à leur tête un décurion d'un grade supérieur. Puis venait le groupe de cinquante décuries - soit cinq cents hommes - lui aussi pourvu d'un chef. Enfin deux de ces compagnies de cinq cents hommes étaient commandées par un général. On conçoit qu'un tel système permettait à l'Inca de tenir étroitement le pays en main.",
    },
    {
        id: 74,
        nom: 'Rastapopoulos',
        prenom: 'Roberto',
        picture: '74.jpg',
        profession: 'Chef de gang, criminel',
        personnage: "Génie du mal, ennemi du bien, grand requin nageant dans les eaux troubles internationales, Rastapopoulos a trouvé en Tintin « l'empêcheur de danser en rond » qui ne cesse de l'irriter. Oeuvrant d'abord dans l'industrie cinématographique, il a versé dans le trafic d'influences et dans celui des stupéfiants. Grand Maître d'une organisation occulte dont les ramifications ont envahi toute la planète. Rastapopoulos, nom à consonance grecque. Roberto, prénom à consonance italienne. Figure emblématique du mauvais et incarnation de la criminalité en smoking. Chef de gang de haute volée, répugnant individu faisant preuve du plus mauvais goût moral et vestimentaire, Roberto Rastapopoulos est un autre mesquin, un autre médiocre, un parvenu qui s'imagine magnifique. (Galerie de Portraits dans Numa Sadoul, Tintin et Moi, p.249). Rastapoupulos est déjà présent dans Tintin en Amérique. En effet, il est protocolairement installé à la gauche de Tintin lors de la soirée de gala offerte en l'honneur du héros, au terme de ses aventures américaines. Dans Les Cigares du Pharaon, Tintin croise sa route sur le paquebot Epomeo qui les emmène tous deux à Port-Saïd. Le milliardaire, directeur de la célèbre firme de cinéma, Cosmos Pictures, se rend en Arabie via l'Egypte afin d'y superviser le tournage de l'une de ses nouvelles superproductions. En réalité, Rastapopoulos dirige une puissante organisation de trafic d'opium dont il est le  Grand Maître  sa félonie sera enfin révélée dans Le Lotus bleu. Génie du mal incontestablement doué d'un entregent peu commun, il réapparaîtra dans Coke en stock sous le pseudonyme de Marquis de Gorgonzola. Enfin dans Vol 714 pour Sydney son rôle est devenu pathétique. Le terrible malfaiteur qui fréquentait la jet-set ne se comporte plus qu'en pitoyable aventurier. Il est ridicule.",
    },
    {
        id: 75,
        nom: 'Ridgewell',
        prenom: 'Mike',
        picture: '75.jpg',
        profession: 'Explorateur',
        personnage: "Ridgewell est un explorateur fuyant la civilisation. Pourquoi a-t-il choisi l’exil de la civilisation pour embrasser la vie primitive des Arumbayas, Indiens qui vivent au coeur de la jungle dans des cases en pisé ? Hergé reste discret sur le sujet. Mais il est clair que l’explorateur porte en lui le dégoût du monde moderne : « Tant pis ! Ou plutôt tant mieux, car j’ai décidé de ne plus jamais retourner dans le monde civilisé. Je suis heureux ici, parmi les Arumbayas dont je partage la vie... » un état d’esprit contraire à celui de la colonisation « civilisatrice » en vogue dans les années 30. Mieux, il se fond dans un mode de vie en adoptant les techniques de survie locales : il utilise la sarbacane. Hergé s’est inspiré de Percival Harrison Fawcett, ancien colonel artilleur de l’Armée des Indes, disparu en 1925, à l’âge de 57 ans, en compagnie de son fils aîné Jack et d’un ami de ce dernier, Raleigh Rimmel, tous deux âgés de 22 ans, en Amazonie brésilienne, au nord de l’État du Mato Grosso.",
    },
    {
        id: 76,
        nom: 'Rizotto',
        prenom: 'Bernardo',
        picture: '76.jpg',
        profession: 'Photographe, journaliste',
        personnage: "Le dynamique reporter photographe, qui fait toujours équipe avec son confrère Jean-Loup de la Batellerie, rédacteur à « Paris-Flash » n’apparaît jamais que bardé de son matériel photographique. Il couvre en compagnie de son confrère l’affaire du faux mariage de la Castafiore à Moulinsart (1963) et le scandale des Picaros (1976). Il est Envoyé Spécial en Ecosse en 1966 à l’occasion du mystère de l’Île Noire (lors du remake de cette aventure) ; on aperçoit page 61 parmi la foule des journalistes qui assaillent Tintin lors de son retour du château de Ben-More. C’est probablement lui qui vendit au Daily Telegraph le reportage photographique sur les faux-monnayeurs qu’Hergé nous livre à la fin de l’album. Son nom est inspiré du fameux plat italien à base de riz !",
    },
    {
        id: 77,
        nom: 'Lampion',
        prenom: 'Seraphin',
        picture: '77.jpg',
        profession: 'Courtier en assurance',
        personnage: "Ce qui fait le charme et l'attrait des Aventures de Tintin, c'est, entre autres, cette faculté peu commune qu'avait Hergé de restituer le monde dans sa diversité, qu'il s'agisse de lieux ou, surtout, des acteurs de ses histoires. Dans sa galerie de personnages régulièrement enrichie, il en manquait un : le casse-pieds intégral. L'Affaire Tournesol va y remédier. Après avoir hésité longtemps, Hergé se décida : son nouveau personnage s'appellerait Lampion. Comme d'habitude, il avait dressé une liste de noms possibles, qu'il avait écartés les uns après les autres. Il avait ainsi rejeté Crampon, qu'il trouvait trop explicite et d'une sonorité trop cassante. Il trancha donc pour Lampion, inséparable depuis lors de son œuvre. Il lui donna un prénom qui contredisait sa personnalité : Séraphin. Le mot Lampion désigne à l'origine une lanterne. Séraphin Lampion est courtier en assurances pour les Assurances Mondass. Il ne cesse d'ailleurs jamais de tenter de vendre une de ces polices d'assurances aux gens qu'il rencontre, aux grands dams de ceux-ci. Lors de ses entretiens avec Numa Sadoul, Hergé raconte :  C'est dans le passé que j'ai puisé le modèle de Lampion. Pendant la guerre, alors que j'habitais Boitsfort, je reçois la visite d'un brave homme qui venait me vendre je ne sais plus quoi, qui s'assied et qui me dit, en me désignant mon fauteuil : Mais asseyez-vous donc !  . L'importun dans toute sa splendeur ! Hergé avait également remarqué que l'une des caractéristiques du Bruxellois ou de ce qu'il appelait le Belgicain était le fait qu'il porte, en même temps, une ceinture et des bretelles, une double sécurité fort convenable pour un placier en assurances ! Sa famille est horrible : la femme, les enfants, la belle-mère, tout ce petit monde est effroyable ! Dans l'Affaire Tournesol, ils mettent à sac le château de Moulinsart. Sans y avoir été convié, celui-ci s'est installé à Moulinsart pour le reste des vacances avec sa petite famille : sa femme, sa belle-mère et ses sept rejetons effroyables, dont des jumeaux. Le professionnel de l'ennui, tellement satisfait, tellement plein de lui-même, laissant à dix longueurs tous ses concurrents au championnat des enquiquineurs. Son autosatisfaction, sa suffisance affichée, sa vulgarité sans retenue, son sourire permanent, ses interminables monologues, exaspèrent Haddock, c'est peu dire, au moins autant que ses amis.  ",
        personnage_suite: "Comme tant de fanfarons, Lampion se double d'un poltron. Décontenancé par l'éclatement sans raison apparente de son verre de whisky, il prend prétexte de la fin de l'orage pour enfiler son veston et son manteau et quitter les lieux. Tintin et Haddock le retrouvent ensuite tapi dans les buissons du parc du château, affirmant qu'on a tenté de l'assassiner. Á la fin de l'histoire, à la simple évocation de la scarlatine par le professeur Tournesol, il plie bagages et quitte précipitamment Moulinsart avec son horrible famille."

    },
    {
        id: 78,
        nom: 'Sanzot',
        prenom: 'Pierre',
        picture: '78.jpg',
        profession: 'Boucher',
        personnage: "Monsieur Sanzot est un digne représentant de cette catégorie de petits indépendants que nous connaissons tous : les joues rebondies et bien rouges, la calvitie assez prononcée et l’air fatigué des gens qui se lèvent tôt pour travailler dans l’atelier de leur commerce. C’est l’abonné au téléphone le plus célèbre des Aventures de Tintin. Mais il reste imperturbable sous la pluie des faux appels. Un « running gag ». La boucherie Sanzot, c’est typiquement un de ces gags qui courent sur plusieurs pages, parfois sur plusieurs albums des Aventures de Tintin et qui font le délice d’Hergé. Que sait- on alors de la boucherie Sanzot et de son propriétaire ? Peu de choses, sinon que le boucher (ou un de ses commis) livre ses commandes dans un «Combi Volkswagen» et qu’il est particulièrement serviable. Et si l’on découvre enfin son visage, sa calvitie et sa petite moustache, la vision de son étal, qui affiche banalement quelques saucissons et pièces de viande, nous laisse sur notre faim quant à la psychologie du personnage. ",
    },
    {
        id: 79,
        nom: 'Ramirez',
        prenom: 'Javier',
        picture: '79.jpg',
        profession: 'homme de main de R.W. Chicklet',
        personnage: "C’est bien connu, s’il faut éliminer une personne, il est préférable de passer par plusieurs intermédiaires et compter sur un réseau en évitant que le commanditaire soit en contact avec l’exécutant. Rodriguez est chargé par R.W.Chicklet de faire éliminer Tintin pour 10 000 dollars. Il utilise Pablo pour accomplir cette tâche qu'il paye 5 000 dollars. ",
    },
    {
        id: 80,
        nom: 'Ronchon',
        prenom: 'Fernand',
        picture: '80.jpg',
        profession: 'Colonel à la retraite',
        personnage: "Ce locataire de l'immeuble du 21 rue de Londres, où habitait le sculpteur Balthazar porte le grade de colonel. S’il faut présumer qu’il est à la retraite vu son âge avancé, ce figurant de première classe garde toute sa verve de militaire et ne recule devant aucun danger, sabre à la main…et, accompagné de sa troupe pour lutter contre la peur des esprits !",
    },
    {
        id: 81,
        nom: 'Szut',
        prenom: 'Piotr',
        picture: '81.jpg',
        profession: 'Pilote d\'avions, mercenaire',
        personnage: "Être affublé d’un nom qui ressemble à une injure courante dans une autre langue : c’est le difficile destin de Piotr Szut, pilote mercenaire estonien. Le nom même de Szut vient très certainement de celui d’Yvan Szücs qui a travaillé sur les premiers dessins animés de Tintin dans les années 1950. Il est surnommé « mitrailleur à bavette » par le capitaine Haddock. Il est borgne, ce qui peut paraître surprenant pour un pilote, mais pas impossible (le grand pilote de chasse japonais Saburo Sakai avait lui aussi perdu l’usage de son œil droit mais continua à combattre). Dans Coke en Stock, Szut va changer de camp et le bandit qui a coulé le bateau de Tintin deviendra l’ami sur lequel on peut compter. On le retrouve plus tard (Vol 714 pour Sydney) à l’aéroport de Jakarta où il est devenu pilote du jet privé de Laszlo Carreidas.",
    },
    {
        id: 82,
        nom: 'Tapioca',
        prenom: 'Alvaro',
        picture: '82.jpg',
        profession: 'Dictateur, chef politique',
        personnage: "Il est de nationalité san-théodorienne. Son nom est déjà cité dans L’Oreille cassée. Il est connu pour être un tyran cruel et vaniteux ! Il est l’éternel rival du général Alcazar. Il correspond assez bien à l’image que l’on se fait d’un dictateur. Une fougue peu commune et une mauvaise foi très méso-américaine colorent la personnalité du général sans toutefois le rendre sympathique. Haddock brosse merveilleusement le portrait de tapioca en le qualifiant de « Mussolini de carnaval ». On remarque avec étonnement l’héroïsme inattendu de ce sinistre personnage qui préfère la mort au déshonneur. Il ne sera finalement pas fusillé. On ne respecte plus rien, hélas ! Le tapioca est une fécule, utilisée en cuisine, produite à partir des racines du manioc amer (toxique avant traitement) séchées puis traitées. Son goût est neutre.",
    },
    {
        id: 83,
        nom: 'Taupe-au-regard-perçant',
        prenom: 'Gall',
        picture: '83.jpg',
        profession: 'Grand Sachem de la tribu des Pieds-Noirs',
        personnage: "N’hésite pas à défendre son territoire et sa tribu contre l'envahisseur blanc. Malheureusement, il se trompe d’ennemi en faisant Tintin prisonnier.",
    },
    {
        id: 84,
        nom: 'Tchang',
        prenom: 'Yuan',
        picture: '84.jpg',
        profession: 'Etudiant en art',
        personnage: "Un jeune Chinois fait basculer Les Aventures de Tintin... Le phénomène est unique dans l’oeuvre d’Hergé : Tchang, personnage qui n’apparaît en fait que dans une quinzaine de pages des Aventures de Tintin, a joué un rôle fondamental dans l’évolution du contenu du récit, symbolisant l’ouverture au monde du créateur. A part la notable exception d’Al Capone, c’est aussi le seul personnage réel qui figure sous son nom dans l’oeuvre. Tchang Tchong-jen était un jeune étudiant des Beaux-Arts, qui étudiait à Bruxelles. L’abbé Gosset était lecteur de Tintin mais aussi aumônier des étudiants chinois à Louvain. Ayant appris qu’après l’Egypte et l’Inde, Tintin allait se rendre en Chine, il mit Hergé en garde contre les préjugés occidentaux courants à l’époque et l’invita à rencontrer un jeune Chinois. C’est Tchang. Pour Hergé, c’était comme ouvrir les yeux. « J’ai découvert un monde nouveau », explique Hergé. Bien entendu, Tintin était depuis toujours dans le camp de ceux qui défendent le bon droit et luttent contre la tyrannie. Mais la découverte authentique d’une vraie civilisation par le simple contact avec un jeune homme dont le pays connaît la guerre, l’occupation et la famine va changer la manière de raconter d’Hergé, qui va axer plus systématiquement ses récits sur la dénonciation de la guerre, des trafics en tous genres et de la manipulation des peuples. Le Lotus bleu est d’ailleurs un album où l’humour se fait rare au profit d’une émotion plus forte. Tintin pleure pour la première fois… Plus étonnant encore est le destin du vrai Tchang. La guerre rompit le contact entre les deux hommes pendant 35 ans et Tintin au Tibet fut écrit plus de vingt ans après leur rencontre, Tintin refusant de croire à la mort de Tchang comme Hergé refusait de croire à la disparition de son ami. Des retrouvailles tardives, deux ans avant la mort d’Hergé, comblèrent, dans la réalité, le fossé qu’avait déjà rempli Tintin en allant sauver Tchang au coeur de la montagne blanche… ",
        personnage_suite: "Symbolisant cette fraternité en humanité que Tchang et Tintin ont établie d’emblée après le sauvetage de la noyade, les deux personnages ne se quitteront plus d’une semelle jusqu’au départ de Tintin de Chine, la larme à l’oeil et le mouchoir blanc de la paix agité. Tchang devient d’emblée le double de Tintin, l’éclairant sur les pièges de son pays et parvenant à lui rendre trois fois la pareille. D’abord en le sauvant des griffes des Dupondt, puis en le faisant échapper à un attentat au faux appareil photo piégé et enfin en lui sauvant littéralement la tête du fil du sabre de Didi en prenant la tête des troupes des fils du Dragon cachés dans des tonneaux d’opium. Même taille, même âge, même endurance, même courage (« à deux, nous serions plus forts », dit Tchang), même habileté face aux forbans (la substitution de la lettre de mission des Dupondt), même absence de famille (les deux n’ont pas de parents apparents), leur destin semble si proche. Même au-delà de la vraisemblance : en quelle langue ces deux-là échangent-ils leur point de vue ? Si le vrai Tchang a appris un français très correct en Belgique, il est peu vraisemblable qu’un jeune orphelin chinois égaré dans les inondations du Yang-Tsé parle français ou anglais…"

    },
    {
        id: 85,
        nom: 'Tharkey',
        prenom: 'Chaya',
        picture: '85.jpg',
        profession: 'Sherpa, guide de montagne',
        personnage: "Le petit sherpa imaginé par Hergé est plus qu’un simple personnage exotique destiné à amener une certaine couleur locale. Tharkey est un véritable portrait psychologique mis en scène par Hergé. Ce persuasif garçon qui refuse au début de l’album une mission qu’il juge inutile et dangereuse sera bientôt gagné par la force de caractère qui anime Tintin tout au long de cette aventure. Tharkey est un vrai chic type.",
    },
    {
        id: 86,
        nom: 'Bolero y Calamares',
        prenom: 'Porfirio',
        picture: '86.jpg',
        profession: 'Savant',
        personnage: "Savant espagnol, Porfirio Bolero y Calamares est professeur à l’université de Salamanque. Il a participé à l’expédition polaire à bord de l’Aurore (L’Étoile mystérieuse).",
    },
    {
        id: 87,
        nom: 'Cantonneau',
        prenom: 'Paul',
        picture: '87.jpg',
        profession: 'Professeur à l\'Université de Fribourg',
        personnage: "Savant suisse, il est membre de l’expédition polaire à bord de l’Aurore (L’Étoile mystérieuse) mais également membre de l’expédition Sanders-Hardmuth en Amérique du Sud. Il sera victime de la malédiction des boules de cristal et tombera dans un sommeil léthargique jusqu’au moment où le grand prêtre Inca détruira sa statuette.",
    },
    {
        id: 88,
        nom: 'Charlet',
        prenom: 'Marc',
        picture: '88.jpg',
        profession: 'Professeur à l\'Université de Fribourg',
        personnage: "Il fait partie de l’expédition Sanders-Hardmuth. Prévenu par Tintin de la malédiction des boules de cristal, il en sera lui aussi victime alors qu’il tentait de rejoindre le jeune reporter.",
    },
    {
        id: 89,
        nom: 'Boullu',
        prenom: 'Yvonne',
        picture: '89.jpg',
        profession: 'Femme au foyer',
        personnage: "Épouse de Monsieur Boullu, le marbrier. Elle tâche de protéger son mari contre les récriminations du capitaine Haddock.",
    },
    {
        id: 90,
        nom: 'Tintin',
        prenom: 'N.C',
        picture: '90.jpg',
        profession: 'Reporter, journaliste',
        personnage: "Tintin. Ce n'est ni un nom ni un prénom, c'est beaucoup plus : Tintin c'est un univers, un mythe, une saga. C'est le héros que tous les jeunes de 7 à 77 ans veulent être – ou deviennent – lorsqu'ils plongent dans les aventures de Tintin. Seize, dix-sept ans (dix-huit tout au plus !), même s'il fête son 90e anniversaire en 2019 ! Sa date de naissance officielle est le 10 janvier 1929. Mais depuis tout ce temps, il n'a pas pris une ride. « Depuis les Soviets... il n'a pratiquement pas évolué, il est toujours une ébauche ». Et c'est son père qui le dit ! (Numa Sadoul, Tintin et moi, Casterman, p.40) Tintin est né de la plume de ce père : Georges Remi, dit Hergé, dessinateur belge mondialement connu. Ce fils spirituel est plus qu’un fils adoptif ! Hergé est formel : « Je l’ai élevé, protégé, nourri, comme un père élève son enfant ». (Numa Sadoul, Tintin et moi, Casterman, p.66). Au fil de ses aventures, Tintin s'est entouré de nombreux personnages qui lui sont devenus familiers. D’abord Milou, il est certes un animal mais il est surtout le fidèle compagnon de Tintin, d’abord par la parole, ensuite par la pensée et par le coeur. Tchang ensuite, qui devient un ami pour la vie, presque un frère. Le capitaine Haddock ensuite, qui est prêt à donner sa vie pour son jeune ami. Et tous les autres, la Castafiore, le professeur Tournesol, Dupond et Dupont, Nestor, etc... En d’autres mots : la famille Tintin ! Reporter, à n'en pas douter. Tintin se lance dans la vie comme envoyé spécial pour Le Petit Vingtième en Russie. Il y écrit son premier et dernier grand reportage, mais durant toute son existence, il gardera cette curiosité et cette volonté de faire jaillir la vérité. Hergé était un homme de presse, son fils a hérité de cette vocation. Un seul signe, mais très particulier. Sa houppe légendaire, bien sûr ! Toutefois, celle-ci n’a pas toujours existé. Dans Tintin au pays des Soviets, notre héros a ses cheveux coiffés vers l’avant durant huit planches. Les lamas tibétains l’ont nommé « Cœur Pur » et il n’y a pas moyen de mieux décrire l’âme de notre personnage. Tintin, c’est peut-être le héros que tout le monde voudrait être, mais c’est certainement l’ami que tout le monde voudrait avoir, cet ami qui va jusqu’au bout pour tous ceux qui lui sont chers.",
    },
    {
        id: 91,
        nom: 'Halvin',
        prenom: 'Tom',
        picture: '91.jpg',
        profession: 'brigand',
        personnage: "Il est l’ennemi inséparable de Tintin tout au cours de ce récit congolais. D’abord, il voyage clandestinement à bord du paquebot qui emmène Tintin au Congo. Il suit Tintin comme son ombre et de fait il est un de ces exécuteurs de la bande à A.C. (Al Capone) et sera d’ailleurs le « serviteur » ou « nettoyeur » de Gibbons. Il échouera dans ses tentatives d’éliminer Tintin et juste retour des choses, il mourra atrocement dévoré par les crocodiles.",
    },
    {
        id: 92,
        nom: 'Triboulet',
        prenom: 'Eugène',
        picture: '92.jpg',
        profession: 'docteur',
        personnage: "Médecin de son état, suspecté par Tintin d’avoir voulu l’écraser, s’avère en réalité un innocent personnage qui vient compléter cette longue série de personnages secondaires des aventures de Tintin. Il réside au 120 avenue Troubadour.",
    },
    {
        id: 93,
        nom: 'Trujillo',
        prenom: 'José',
        picture: '93.jpg',
        profession: 'Propriétaire d\'une ferme',
        personnage: "Don José Trujillo est propriétaire d’une hacienda et accorde l’hospitalité à Tintin qui vient d’échapper à ses poursuivants de l’armée de Nuevo Rico. Tintin qui souhaite poursuivre le long du fleuve Badurayal pour aller chez les Arumbayas sollicite un guide.",
    },
    {
        id: 94,
        nom: 'Van Damme',
        prenom: 'Jean',
        picture: '94.jpg',
        profession: 'Cuisinier',
        personnage: "Cuisinier à bord de L’Aurore, Van Damme rencontre Alphonse, un ami, dans un bistrot avant son embarquement sur le Sirius comme cuisinier. Van Damme est un homme heureux tant que Milou reste hors de sa cuisine.",
    },
    {
        id: 95,
        nom: 'Wizskizsek',
        prenom: 'Dominic',
        picture: '95.jpg',
        profession: 'Commandant de gendarmerie',
        personnage: "Tintin ne s’est pas assez méfié de l’uniforme. Il fait trop confiance au commandant de gendarmerie qui arbore une moustache impériale. Le (mauvais) sort a voulu qu’il tombe sur Wizskizsek, odieux conspirateur contre le trône de son monarque Muskar II. Wizskizsek fait partie des conjurés comme le commandant Zlip. Son expression favorite : « avec des « si » on met Klow dans une bouteille ». Hergé s’amuse en nommant ses personnages : ce nom à résonnance « syldave » s’inspire du « whisky sec » en français.",
    },
    {
        id: 96,
        nom: 'Yeti',
        prenom: 'Migou',
        picture: '96.jpg',
        profession: 'animal sauvage',
        personnage: "Connu sous l’appellation « abominable homme des neiges », c’est un personnage d’une très grande discrétion (on ne l’aperçoit qu’après 54 pages de suspense insupportable) et pourtant il est omniprésent dans notre inconscient. Il possède un cœur d’or et souffre énormément de la solitude. C’est grâce à lui que le jeune chinois Tchang a pu survivre dans la chaîne himalayenne et être sauvé par Tintin. Un rien l’effraye: l’éclair d’un flash, un éternuement du capitaine Haddock etc…Son étiquette d’« abominable homme des neiges » ne colle donc pas du tout à ce personnage très humain ! Il a tendance à chaparder les bouteilles de whisky !",
    },
    {

        id: 97,
        nom: 'Jacinto',
        prenom: 'Zorrino',
        picture: '97.jpg',
        profession: 'Marchand d\'orange de Jauga, guide',
        personnage: "Ils ne sont pas légion. Les enfants ou les jeunes adolescents présents dans Les Aventures de Tintin se comptent sur les doigts d’une main. Tchang, Abdallah et Zorrino en forment le trio vedette. Zorrino, un « petit renard » au cœur généreux. Le jeune garçon est méprisé par les descendants des colons espagnols parce qu’il est un Indien quechua, terme qui désigne la civilisation qui a fondé, vers le XIIe siècle, le royaume de Cuzco, avant d’être inclue dans la dynastie inca au XIIIe siècle. D’où est né Zorrino, le petit garçon dont le nom signifie en espagnol «petit renard», ou évoque la fourrure très souple et soyeuse de la zorille ? Sans aucun doute de la nécessité de trouver un personnage qui serve de passeur entre deux civilisations, l’une contemporaine, et l’autre, miraculeusement préservée, des Incas. Authentique indien ! Zorrino est un authentique Indien. Hergé va l’habiller comme tel, lui choisissant une garde-robe typiquement péruvienne. Zorrino porte un «chullo», le fameux bonnet péruvien originaire des hauts plateaux des Andes, lors de sa première apparition. Fabriqué à base de laine d’alpaga, le « chullo » est un élément indissociable de la culture péruvienne. Quand il s’agira de guider Tintin à travers la cordillère, Zorrino passera un magnifique poncho qui, depuis des millénaires, fait office de vêtement de survie.",
    }



];

module.exports = series